export class Manga {
  constructor(volume, capitolo, titolo) {
    this.Volume = volume;
    this.Capitolo = capitolo;
    this.Titolo = titolo;
  }
}

export class MangaList {
  constructor(mangaArray) {
    this.mangaArray = [
      new Manga(1, 1, "Romance Dawn, l'alba di una grande avventura"),
      new Manga(1, 2, "Rufy, il ragazzo dal cappello di paglia"),
      new Manga(1, 3, "Ecco Zoro, il cacciatore di pirati"),
      new Manga(1, 4, "Il capitano di vascello morgan mano d'ascia"),
      new Manga(1, 5, "Il Re Dei Pirati e il Più Grande Spadaccino"),
      new Manga(1, 6, "Il primo compagno"),
      new Manga(1, 7, "Amici"),
      new Manga(1, 8, "Ecco Nami"),
      new Manga(2, 9, "Femme fatale"),
      new Manga(2, 10, "Incidente al bar"),
      new Manga(2, 11, "Fuga"),
      new Manga(2, 12, "Il Cane"),
      new Manga(2, 13, "Tesoro"),
      new Manga(2, 14, "Imprudente"),
      new Manga(2, 15, "Gong"),
      new Manga(2, 16, "Versus! I pirati di Buggy!"),
      new Manga(2, 17, "Livelli diversi"),
      new Manga(3, 18, "Il pirata buggy il clown"),
      new Manga(3, 19, "Il frutto del diavolo"),
      new Manga(3, 20, "La via del ladro"),
      new Manga(3, 21, "Il villaggio"),
      new Manga(3, 22, "Sei una strana bestia"),
      new Manga(3, 23, "Ecco capitan Usopp"),
      new Manga(3, 24, "Qualcosa che non posso rinnegare"),
      new Manga(3, 25, "800 bugie"),
      new Manga(3, 26, "Il piano di capitan kuro"),
      new Manga(4, 27, "Il piano"),
      new Manga(4, 28, "Luna crescente"),
      new Manga(4, 29, "La salita "),
      new Manga(4, 30, "Great!"),
      new Manga(4, 31, "Verità"),
      new Manga(4, 32, "Disastro"),
      new Manga(4, 33, "L'uomo silenzioso"),
      new Manga(4, 34, "Il maggiordomo Krahador"),
      new Manga(4, 35, "Una salita ostica"),
      new Manga(5, 36, "Inseguimento!"),
      new Manga(5, 37, "Il pirata kuro lo stratega"),
      new Manga(5, 38, "Pirati"),
      new Manga(5, 39, "Per chi suona la campana "),
      new Manga(5, 40, "La ciurma dei pirati di Usopp "),
      new Manga(5, 41, "Per mare"),
      new Manga(5, 42, "Yosaku e Johnny"),
      new Manga(5, 43, "Ecco Sanji"),
      new Manga(5, 44, "I tre cuochi"),
      new Manga(6, 45, "Prima della tempesta"),
      new Manga(6, 46, "Un ospite sgradito"),
      new Manga(6, 47, "L'ammiraglio della flotta pirata, don krieg"),
      new Manga(6, 48, "Lascia perdere quella rotta"),
      new Manga(6, 49, "Tempesta"),
      new Manga(6, 50, "Ognuno per la propria strada"),
      new Manga(6, 51, "Roronoa Zoro cade in mare"),
      new Manga(6, 52, "Giuramento"),
      new Manga(6, 53, "Sabagashira I"),
      new Manga(7, 54, "Pearl Titolo-san"),
      new Manga(7, 55, "Jungle blood"),
      new Manga(7, 56, "Non ci penso nemmeno"),
      new Manga(7, 57, "A causa dei sogni"),
      new Manga(7, 58, "Vecchio di merda"),
      new Manga(7, 59, "Debito"),
      new Manga(7, 60, "Tra giusto e sbagliato"),
      new Manga(7, 61, "Demone"),
      new Manga(7, 62, "MH"),
      new Manga(8, 63, "Io non morirò"),
      new Manga(8, 64, "Grande lancia da battaglia"),
      new Manga(8, 65, "Preparazione"),
      new Manga(8, 66, "La distruzione della lancia"),
      new Manga(8, 67, "La zuppa"),
      new Manga(8, 68, "La quarta persona"),
      new Manga(8, 69, "Arlong park"),
      new Manga(8, 70, "La grande avventura del prode Usopp"),
      new Manga(8, 71, "Il re di tutte le creature viventi"),
      new Manga(9, 72, "In base ai propri mezzi"),
      new Manga(9, 73, "Il mostro venuto dalla Grand Line"),
      new Manga(9, 74, "Affari"),
      new Manga(9, 75, "Carte nautiche e uomini-pesce"),
      new Manga(9, 76, "Io dormo"),
      new Manga(
        9,
        77,
        "Il primo passo verso la realizzazione del sogno"
      ),
      new Manga(9, 78, "Bellmère-san"),
      new Manga(9, 79, "Vivere"),
      new Manga(9, 80, "Un crimine è un crimine"),
      new Manga(9, 81, "Lacrime"),
      new Manga(10, 82, "Ok, let's stand up!"),
      new Manga(10, 83, "Rufy in back"),
      new Manga(10, 84, "Morto vivente"),
      new Manga(10, 85, "Santoryu vs Rokutoryu"),
      new Manga(10, 86, "Cavalleria vs karate Uomini-Pesce"),
      new Manga(10, 87, "è finita!"),
      new Manga(10, 88, "Morire!"),
      new Manga(10, 89, "Cambio"),
      new Manga(10, 90, "Cosa sai fare?!"),
      new Manga(11, 91, "Darts"),
      new Manga(11, 92, "Felicità"),
      new Manga(11, 93, "Sta crollando"),
      new Manga(11, 94, "La seconda persona"),
      new Manga(11, 95, "E la girandola gira"),
      new Manga(11, 96, "Il peggiore dell'est"),
      new Manga(11, 97, "Sandai kitetsu"),
      new Manga(11, 98, "Nuvole nere"),
      new Manga(11, 99, "La morte di Rufy"),
      new Manga(12, 100, "La leggenda ha inizio!"),
      new Manga(12, 101, "Reverse Mountain"),
      new Manga(12, 102, "Ecco la Grand Line"),
      new Manga(12, 103, "La balena"),
      new Manga(12, 104, "Il promontorio della promessa"),
      new Manga(12, 105, "Il log pose"),
      new Manga(12, 106, "La città dell'accoglienza"),
      new Manga(12, 107, "Lapidi e chiaro di luna"),
      new Manga(12, 108, "100 cacciatori di taglie"),
      new Manga(13, 109, "Responsabilità"),
      new Manga(13, 110, "La notte infinita"),
      new Manga(13, 111, "Un'organizzazione criminale segreta"),
      new Manga(13, 112, "Rufy vs Zoro"),
      new Manga(13, 113, "Andrà tutto bene"),
      new Manga(13, 114, "Rotta"),
      new Manga(13, 115, "Avventura a Little Garden"),
      new Manga(13, 116, "Immensi"),
      new Manga(13, 117, "Dorry e Brogy"),
      new Manga(14, 118, "Non siamo soli"),
      new Manga(14, 119, "Espediente"),
      new Manga(14, 120, "Le lacrime del demone rosso"),
      new Manga(14, 121, "Lo sapevo"),
      new Manga(14, 122, "I morti non servono a nulla"),
      new Manga(14, 123, "Rufy vs Mr.3"),
      new Manga(14, 124, "Questo tè è davvero delizioso"),
      new Manga(14, 125, "Candle champion"),
      new Manga(14, 126, "Istinto"),
      new Manga(15, 127, "Il lumacofono"),
      new Manga(15, 128, "Bandiera pirata"),
      new Manga(15, 129, "Tutta a dritta!"),
      new Manga(15, 130, "Alla massima velocità"),
      new Manga(15, 131, "''Blink'' wapol"),
      new Manga(15, 132, "Visto?"),
      new Manga(15, 133, "Avventura nel paese senza nome"),
      new Manga(15, 134, "La dottoressa Kureha"),
      new Manga(15, 135, "Lapahn"),
      new Manga(15, 136, "Un uomo chiamato dorton"),
      new Manga(16, 137, "La valanga"),
      new Manga(16, 138, "In cima"),
      new Manga(16, 139, "Ecco Tony Tony Chopper"),
      new Manga(16, 140, "Vita nel castello innevato"),
      new Manga(16, 141, "Medicastro"),
      new Manga(16, 142, "Il teschio ed il ciliegio"),
      new Manga(16, 143, "Inesperto"),
      new Manga(16, 144, "I racconti della neve"),
      new Manga(16, 145, "Volontà ereditata"),
      new Manga(17, 146, "Combattere per proteggere il regno"),
      new Manga(17, 147, "Bugia"),
      new Manga(17, 148, "Indistruttibile"),
      new Manga(17, 149, "Rumble"),
      new Manga(17, 150, "Il Royal Drum Crown 7-Shot Blinking Cannon"),
      new Manga(17, 151, "Il cielo di Drum"),
      new Manga(17, 152, "Luna piena"),
      new Manga(17, 153, "I ciliegi di Hiluluk"),
      new Manga(17, 154, "Verso Alabasta"),
      new Manga(17, 155, "Il pirata Sir Crocodile"),
      new Manga(18, 156, "Tempo di okama"),
      new Manga(18, 157, "Ecco Ace"),
      new Manga(18, 158, "Sbarco ad Alabasta"),
      new Manga(18, 159, "A presto"),
      new Manga(18, 160, "Spiders cafè, 8 in punto"),
      new Manga(18, 161, "Elumalu, la città verde"),
      new Manga(18, 162, "Avventura nel regno della sabbia"),
      new Manga(18, 163, "Yuba, la città dei ribelli"),
      new Manga(18, 164, "Ami questo paese?"),
      new Manga(18, 165, "Operazione Utopia"),
      new Manga(18, 166, "Rufy vs Bibi"),
      new Manga(19, 167, "Il campo di battaglia"),
      new Manga(19, 168, "Rainbase, la città dei sogni"),
      new Manga(19, 169, "Il più forte guerriero del regno"),
      new Manga(19, 170, "Si comincia"),
      new Manga(19, 171, "Kohza, il leader ribelle"),
      new Manga(19, 172, "Ribellione"),
      new Manga(19, 173, "Coccobanana"),
      new Manga(19, 174, "Mr. Prince"),
      new Manga(19, 175, "Libertà"),
      new Manga(19, 176, "Rush!"),
      new Manga(20, 177, "30 milioni vs 81 milioni"),
      new Manga(20, 178, "Livello Grand Line"),
      new Manga(20, 179, "La battaglia decisiva sarà al Alubarna"),
      new Manga(20, 180, "Gli animali del regno di Alabasta"),
      new Manga(
        20,
        181,
        "Lo stratagemma della squadra delle super anatre dal becco macchiato"
      ),
      new Manga(20, 182, "Urla di rabbia"),
      new Manga(20, 183, "Il comandante Karu"),
      new Manga(20, 184, "Via cumulo di terra numero 4"),
      new Manga(20, 185, "Wow... Buono a sapersi..."),
      new Manga(20, 186, "Four"),
      new Manga(21, 187, "Alla pari"),
      new Manga(21, 188, "Okama Kenpo"),
      new Manga(21, 189, "Two"),
      new Manga(21, 190, "Clima Tact"),
      new Manga(21, 191, "La donna che controlla il clima"),
      new Manga(21, 192, "Attenzione ai tornado"),
      new Manga(21, 193, "Utopia"),
      new Manga(21, 194, "Tagliare l'acciaio"),
      new Manga(21, 195, "Mr. Bushido"),
      new Manga(22, 196, "One"),
      new Manga(22, 197, "I leader"),
      new Manga(22, 198, "4=15 del pomeriggio"),
      new Manga(22, 199, "Speranza"),
      new Manga(22, 200, "Acqua Rufy"),
      new Manga(22, 201, "Nico Robin"),
      new Manga(22, 202, "La tomba reale"),
      new Manga(22, 203, "Puzza di coccodrillo"),
      new Manga(22, 204, "Sangue"),
      new Manga(22, 205, "La base segreta del clan della sabbia"),
      new Manga(23, 206, "Fuoco alle polveri"),
      new Manga(23, 207, "Incubo"),
      new Manga(23, 208, "La divinità protettrice"),
      new Manga(23, 209, "Ti supererò"),
      new Manga(23, 210, "Zero"),
      new Manga(23, 211, "Il re"),
      new Manga(23, 212, "Un po' di giustizia"),
      new Manga(23, 213, "VIP"),
      new Manga(23, 214, "Il piano per fuggire dal regno di sabbia"),
      new Manga(23, 215, "L'ultimo valzer"),
      new Manga(23, 216, "L'avventura di Bibi"),
      new Manga(24, 217, "Clandestino a bordo"),
      new Manga(24, 218, "Il motivo per cui il log pose è sferico"),
      new Manga(24, 219, "Masira, il re dei recuperi"),
      new Manga(24, 220, "Due passi sott'acqua"),
      new Manga(24, 221, "I mostri"),
      new Manga(24, 222, "Il grande rookie"),
      new Manga(
        24,
        223,
        "Giuro che non combatterò contro nessuno in questa città"
      ),
      new Manga(24, 224, "Vietato sognare"),
      new Manga(24, 225, "I sogni degli uomini"),
      new Manga(24, 226, "Shojo, il re delle esplorazioni sottomarine"),
      new Manga(25, 227, "Noland il bugiardo"),
      new Manga(
        25,
        228,
        "Montblanc Cricket, l'ultimo capo della coalizione della montagna delle scimmie"
      ),
      new Manga(25, 229, "Andiamo a mangiare"),
      new Manga(25, 230, "Alla ricerca del South Bird"),
      new Manga(25, 231, "Bellamy la iena"),
      new Manga(25, 232, "L'uomo da cento milioni"),
      new Manga(25, 233, "La massima autorità mondiale"),
      new Manga(25, 234, "Abbiate l'accortezza di non dimenticarlo"),
      new Manga(25, 235, "Knock Up Stream"),
      new Manga(25, 236, "La nave vola nel cielo"),
      new Manga(26, 237, "In cielo"),
      new Manga(26, 238, "La porta del paradiso"),
      new Manga(26, 239, "Angel Beach"),
      new Manga(26, 240, "L'energia dei dial"),
      new Manga(26, 241, "Il giudizio divino"),
      new Manga(26, 242, "Criminali di seconda classe"),
      new Manga(26, 243, "Le prove"),
      new Manga(26, 244, "S.O.S"),
      new Manga(26, 245, "Avventura sull'isola di Dio"),
      new Manga(
        26,
        246,
        "Satori, il sacerdote della foresta dei perduti"
      ),
      new Manga(27, 247, "La prova delle sfere"),
      new Manga(27, 248, "Ex Dio vs Sacerdote"),
      new Manga(27, 249, "Il villaggio nascosto fra le nuvole"),
      new Manga(27, 250, "Il drago di sfere"),
      new Manga(27, 251, "Preludio"),
      new Manga(27, 252, "Ricongiungimento"),
      new Manga(27, 253, "Vearth"),
      new Manga(27, 254, "Aubade"),
      new Manga(27, 255, "Il serpentone e il gruppo di ricerca"),
      new Manga(28, 256, "Wiper il demone combattente"),
      new Manga(28, 257, "Dial battle"),
      new Manga(28, 258, "Molteplici direzioni verso sud"),
      new Manga(28, 259, "Zoro il pirata vs Braham il guerriero"),
      new Manga(
        28,
        260,
        "Rufy il pirata vs Wiper il demone combattente"
      ),
      new Manga(
        28,
        261,
        "Gembo il guerriero vs Yama, il comandante della Guardia Sacra"
      ),
      new Manga(28, 262, "Chopper il pirata vs Gedatsu il sacerdote"),
      new Manga(
        28,
        263,
        "Nami la pirata e lo strano cavaliere vs i Vice Comandanti dell'Armata sacra"
      ),
      new Manga(28, 264, "Kamakiri il guerriero vs Dio Ener"),
      new Manga(
        29,
        265,
        "Robin la piratessa vs Yama, il comandante della guardia sacra"
      ),
      new Manga(29, 266, "Chopper il pirata vs Ohm il sacerdote"),
      new Manga(29, 267, "Marcia"),
      new Manga(29, 268, "Suite"),
      new Manga(29, 269, "Concerto"),
      new Manga(29, 270, "Serenata"),
      new Manga(29, 271, "Zoro il pirata vs Ohm il sacerdote"),
      new Manga(29, 272, "Play"),
      new Manga(29, 273, "Quintetto"),
      new Manga(29, 274, "Oratorio"),
      new Manga(29, 275, "Divina Commedia"),
      new Manga(30, 276, "Shandia Rhythm"),
      new Manga(30, 277, "Maxim"),
      new Manga(30, 278, "Konis"),
      new Manga(30, 279, "Rufy il Pirata vs Dio Ener"),
      new Manga(30, 280, "Emersione"),
      new Manga(30, 281, "Deathpiea"),
      new Manga(30, 282, "Desiderio"),
      new Manga(
        30,
        283,
        "In prima linea nel salvataggio in nome dell'amore"
      ),
      new Manga(30, 284, "Ti ringrazio"),
      new Manga(30, 285, "Capriccio"),
      new Manga(31, 286, "Il demone di Shandora"),
      new Manga(31, 287, "Deicidio"),
      new Manga(31, 288, "Maledizione"),
      new Manga(31, 289, "Plenilunio"),
      new Manga(31, 290, "La luce di Shandora"),
      new Manga(31, 291, "Noi siamo qui"),
      new Manga(31, 292, "Incontrando una mezzaluna tra le nuvole"),
      new Manga(31, 293, "Bolero"),
      new Manga(31, 294, "Raigo"),
      new Manga(31, 295, "Giant Jack"),
      new Manga(32, 296, "Situazione ad alta quota"),
      new Manga(32, 297, "Preghiere da terra"),
      new Manga(32, 298, "Canto d'amore"),
      new Manga(32, 299, "Fantasia"),
      new Manga(32, 300, "Sinfonia"),
      new Manga(32, 301, "Sono stato qui"),
      new Manga(32, 302, "Finale"),
      new Manga(32, 303, "I pirati ricchi sfondati"),
      new Manga(32, 304, "Avventura sull'isola lunga"),
      new Manga(32, 305, "Foxy la volpe argentata"),
      new Manga(33, 306, "Donut race"),
      new Manga(33, 307, "Pronti, partenza... donut!"),
      new Manga(33, 308, "Battaglia d'interferenze"),
      new Manga(33, 309, "Groggy monsters"),
      new Manga(33, 310, "Groggy ring"),
      new Manga(33, 311, "Gioco duro"),
      new Manga(33, 312, "Goal!"),
      new Manga(33, 313, "L'evento principale"),
      new Manga(33, 314, "Combattimento!"),
      new Manga(33, 315, "La stanza segreta"),
      new Manga(33, 316, "Anima fraterna"),
      new Manga(34, 317, "K.O."),
      new Manga(34, 318, "Fine dei giochi"),
      new Manga(
        34,
        319,
        "L'ammiraglio Aokiji del quartier generale della marina"
      ),
      new Manga(34, 320, "Un potere straordinario"),
      new Manga(34, 321, "Da uomo a uomo"),
      new Manga(34, 322, "Puffing Tom"),
      new Manga(34, 323, "Water Seven la città dell'acqua"),
      new Manga(34, 324, "Avventura nella città d'acqua"),
      new Manga(34, 325, "Franky Family"),
      new Manga(34, 326, "Iceburg-san"),
      new Manga(34, 327, "Il Dock 1 dell'isola dei cantieri navali"),
      new Manga(35, 328, "L'incidente del sequestro del pirata"),
      new Manga(35, 329, "Il mio nome è Franky"),
      new Manga(35, 330, "Ho deciso!"),
      new Manga(35, 331, "Un grande litigio"),
      new Manga(35, 332, "Rufy vs Usop"),
      new Manga(35, 333, "Capitano"),
      new Manga(35, 334, "L'incidente della stanza chiusa a chiave"),
      new Manga(35, 335, "Avvertimento"),
      new Manga(35, 336, "Rufy vs Franky"),
      new Manga(36, 337, "I guardiani della città dell'acqua"),
      new Manga(36, 338, "Coup de vent"),
      new Manga(36, 339, "Qualche chiacchiera"),
      new Manga(36, 340, "La donna portatrice di sventura"),
      new Manga(36, 341, "Diavolo"),
      new Manga(36, 342, "I messaggeri dell'oscurità"),
      new Manga(36, 343, "Chiper Pol N°9"),
      new Manga(36, 344, "Potere contrapposto"),
      new Manga(36, 345, "Gli infiltrati"),
      new Manga(36, 346, "La nona giustizia"),
      new Manga(37, 347, "Rokushiki"),
      new Manga(37, 348, "Forza combattiva"),
      new Manga(37, 349, "Comune cittadino"),
      new Manga(37, 350, "Il magazzino sotto il ponte"),
      new Manga(37, 351, "Klabautermann"),
      new Manga(37, 352, "Tom's Workers"),
      new Manga(37, 353, "Il leggendario carpentiere"),
      new Manga(37, 354, "Il Treno marino"),
      new Manga(37, 355, "Spandam"),
      new Manga(37, 356, "Tom-san"),
      new Manga(37, 357, "Cutty Flam"),
      new Manga(38, 358, "Resurrezione"),
      new Manga(38, 359, "Bingo"),
      new Manga(38, 360, "Partenza imminente"),
      new Manga(38, 361, "P.S."),
      new Manga(38, 362, "Riflusso di marea"),
      new Manga(38, 363, "Acqua laguna"),
      new Manga(38, 364, "Kokoro"),
      new Manga(38, 365, "Rocketman!"),
      new Manga(38, 366, "Si va in scena"),
      new Manga(38, 367, "Sogeking"),
      new Manga(39, 368, "Battaglia a bordo del treno marino"),
      new Manga(39, 369, "Ramen Kenpo"),
      new Manga(39, 370, "Non sei sola"),
      new Manga(39, 371, "L'ammirevole capitano T-Bone"),
      new Manga(39, 372, "Parage"),
      new Manga(39, 373, "Male necessario"),
      new Manga(39, 374, "Lotta"),
      new Manga(39, 375, "I superuomini di Enies Lobby"),
      new Manga(39, 376, "Ho capito!"),
      new Manga(
        39,
        377,
        "La grande battaglia decisiva sull'isola giudiziaria"
      ),
      new Manga(40, 378, "Il bilancio delle perdite"),
      new Manga(40, 379, "Doriki"),
      new Manga(
        40,
        380,
        "Espresso per l'isola principale di Enies Lobby"
      ),
      new Manga(40, 381, "Licenziati"),
      new Manga(40, 382, "Il covo dei demoni"),
      new Manga(40, 383, "Rufy vs Blueno"),
      new Manga(40, 384, "L'ora del contrattacco"),
      new Manga(40, 385, "C'è solo un modo"),
      new Manga(40, 386, "Senza precedenti"),
      new Manga(40, 387, "Gear"),
      new Manga(40, 388, "Gear Second"),
      new Manga(41, 389, "Risposta"),
      new Manga(41, 390, "Contrattacco"),
      new Manga(41, 391, "La bambina chiamata mostro"),
      new Manga(41, 392, "Dereshi"),
      new Manga(41, 393, "Olvia"),
      new Manga(41, 394, "I demoni di Ohara"),
      new Manga(41, 395, "Ohara vs governo mondiale"),
      new Manga(41, 396, "Saul"),
      new Manga(41, 397, "Raggiungere il futuro"),
      new Manga(41, 398, "Dichiarazione di guerra"),
      new Manga(41, 399, "Saltate nella cascata!!"),
      new Manga(42, 400, "La chiave della libertà"),
      new Manga(42, 401, "Pirati vs CP9"),
      new Manga(42, 402, "Le manette numero 2"),
      new Manga(42, 403, "Mister cavalleria"),
      new Manga(42, 404, "Franky vs Fukuro"),
      new Manga(42, 405, "Potere"),
      new Manga(42, 406, "Seimei Kikan"),
      new Manga(42, 407, "Mostro"),
      new Manga(42, 408, "Il mostro vs Kumadori"),
      new Manga(
        42,
        409,
        "Cattive notizie dalla trasmissione d'emergenza"
      ),
      new Manga(43, 410, "La Nami gigantesca"),
      new Manga(43, 411, "Nami vs Califa"),
      new Manga(43, 412, "Occasione persa"),
      new Manga(43, 413, "Il cacciatore"),
      new Manga(43, 414, "Sanji vs Jabura"),
      new Manga(43, 415, "Heat up!"),
      new Manga(43, 416, "Zoro vs Kaku"),
      new Manga(43, 417, "Ashura"),
      new Manga(43, 418, "Rufy vs Rob Lucci"),
      new Manga(43, 419, "La leggenda dell'eroe"),
      new Manga(44, 420, "Buster Call"),
      new Manga(44, 421, "Gear Third"),
      new Manga(44, 422, "Rob Lucci"),
      new Manga(44, 423, "La leggenda della sirena"),
      new Manga(44, 424, "Nave per la fuga"),
      new Manga(44, 425, "Combattimento disperato sul ponte"),
      new Manga(44, 426, "Nave in attesa del vento"),
      new Manga(44, 427, "Qui non siamo affatto all'inferno!"),
      new Manga(44, 428, "Torniamo indietro!"),
      new Manga(44, 429, "Disfatta totale"),
      new Manga(44, 430, "Cade una soffice neve di ricordi"),
      new Manga(45, 431, "L'amorevole pugno"),
      new Manga(45, 432, "Scatola a sorpresa"),
      new Manga(45, 433, "Il nome di quel mare è..."),
      new Manga(45, 434, "Barbabianca e il Rosso"),
      new Manga(45, 435, "Capiamo ciò che provate..."),
      new Manga(45, 436, "Pants from Frankyhouse"),
      new Manga(45, 437, "Nudo, ma uomo vero"),
      new Manga(45, 438, "Orgoglio"),
      new Manga(45, 439, "Il terzo e il settimo"),
      new Manga(45, 440, "Pugno di fuoco vs Barbanera"),
      new Manga(46, 441, "Duello sull'isola di Banaro"),
      new Manga(46, 442, "Avventura nelle acque malefiche"),
      new Manga(46, 443, "Thriller Bark"),
      new Manga(46, 444, "Avventura sull'isola fantasma"),
      new Manga(46, 445, "The Zombie"),
      new Manga(46, 446, "Il dottor Hogback"),
      new Manga(46, 447, "Gli Zombie a sorpresa"),
      new Manga(46, 448, "Moria"),
      new Manga(46, 449, "I quattro mostri di Thriller Bark"),
      new Manga(47, 450, "General Zombie Night"),
      new Manga(47, 451, "Il wonder garden di Perona!"),
      new Manga(47, 452, "Jigoro del vento"),
      new Manga(
        47,
        453,
        "Cielo coperto con probabili precipitazioni di ossa"
      ),
      new Manga(47, 454, "Canterino"),
      new Manga(47, 455, "Gekko Moria della flotta dei sette"),
      new Manga(47, 456, "Il demone giunto dal regno dei ghiacci"),
      new Manga(47, 457, "Caaarneee!"),
      new Manga(47, 458, "Tutto ma non l'afro!"),
      new Manga(
        47,
        459,
        "Non potrei mai dire= ''Scusa tanto, ma siamo morti''"
      ),
      new Manga(48, 460, "Recuperarle prima che sorga il sole!"),
      new Manga(48, 461, "Ghost Buster"),
      new Manga(48, 462, "L'avventura di Oz"),
      new Manga(48, 463, "Sanji il pirata vs absolom il misterioso"),
      new Manga(48, 464, "Il sogno di Sanji"),
      new Manga(48, 465, "Il pirata Usopp vs la principessa Perona"),
      new Manga(48, 466, "Concluso"),
      new Manga(48, 467, "Zoro il pirata vs Ryuma il samurai"),
      new Manga(48, 468, "Chopper il pirata vs lo spettrale Hogback"),
      new Manga(48, 469, "Venite fuori Mugiwara!!!"),
      new Manga(48, 470, "Oz vs Mugiwara"),
      new Manga(49, 471, "My friend"),
      new Manga(49, 472, "Down"),
      new Manga(49, 473, "Bartolomew Kuma della flotta dei sette"),
      new Manga(49, 474, "Non ci resta che farlo!"),
      new Manga(49, 475, "I pirati della foresta"),
      new Manga(49, 476, "Nightmare Rufy"),
      new Manga(49, 477, "3/8"),
      new Manga(49, 478, "Rufy vs Rufy"),
      new Manga(49, 479, "Guerriero della speranza"),
      new Manga(49, 480, "Intercettamento"),
      new Manga(49, 481, "Shadow's Asgard"),
      new Manga(50, 482, "Arriva l'alba"),
      new Manga(50, 483, "Fine di un sogno"),
      new Manga(50, 484, "Boing"),
      new Manga(
        50,
        485,
        "Equipaggio di Cappello di Paglia= Zoro il cacciatore di pirati"
      ),
      new Manga(50, 486, "Pianoforte"),
      new Manga(50, 487, "Quella canzone"),
      new Manga(50, 488, "La canzone della vita"),
      new Manga(50, 489, "L'ottava persona"),
      new Manga(50, 490, "Ancora li!"),
      new Manga(50, 491, "I piloti dei pesci volanti"),
      new Manga(51, 492, "Duval dalla maschera di ferro"),
      new Manga(51, 493, "Mi conosci"),
      new Manga(51, 494, "La tragedia di Duval"),
      new Manga(51, 495, "Il Cannone Gaon"),
      new Manga(51, 496, "La Mangrovia Yarukiman"),
      new Manga(51, 497, "Avventura nell'isola delle bolle danzanti"),
      new Manga(51, 498, "Le undici Supernove"),
      new Manga(51, 499, "Sabaody Park"),
      new Manga(51, 500, "Fuoco sotto la cenere della storia"),
      new Manga(51, 501, "Il mondo inizia a ribollire"),
      new Manga(51, 502, "L'incidente dei dragoviani"),
      new Manga(52, 503, "Un'isola nel caos"),
      new Manga(52, 504, "Pirati in prima linea all'attacco!!"),
      new Manga(52, 505, "Orso"),
      new Manga(52, 506, "Roger e Rayleigh"),
      new Manga(52, 507, "Lo sbarco di Kizaru"),
      new Manga(52, 508, "L'isola del massacro"),
      new Manga(52, 509, "Kizaru contro 4 capitani"),
      new Manga(
        52,
        510,
        "La squadra di Cappello di Paglia contro la macchina da guerra"
      ),
      new Manga(52, 511, "Sentomaru e la sua ascia"),
      new Manga(52, 512, "La scomparsa di Zoro"),
      new Manga(53, 513, "Non ho potuto nemmeno..."),
      new Manga(53, 514, "Funghi che crescono sul corpo"),
      new Manga(53, 515, "Avventura nell'isola delle donne"),
      new Manga(53, 516, "L'imperatrice pirata, Boa Hancock"),
      new Manga(53, 517, "Il bagno"),
      new Manga(53, 518, "L'arena"),
      new Manga(53, 519, "L'indole di un re"),
      new Manga(53, 520, "L'occhio della Gorgone"),
      new Manga(
        53,
        521,
        "L'artiglio dei draghi che si ergono nei cieli"
      ),
      new Manga(53, 522, "Malattia mortale"),
      new Manga(54, 523, "Inferno"),
      new Manga(54, 524, "Nessuno può fermarci adesso"),
      new Manga(54, 525, "Impel Down, la prigione subacquea"),
      new Manga(54, 526, "Avventura nella grande prigione"),
      new Manga(54, 527, "Lv.1, l'inferno purpureo"),
      new Manga(54, 528, "Jinbe, il cavaliere dei mari"),
      new Manga(54, 529, "L'inferno delle bestie"),
      new Manga(54, 530, "Da un inferno all'altro"),
      new Manga(54, 531, "L'inferno dell'inedia"),
      new Manga(54, 532, "Minotauro, la guardia demoniaca"),
      new Manga(55, 533, "Livello quattro= l'inferno bollente"),
      new Manga(55, 534, "Capo guardiano magellan vs il pirata"),
      new Manga(55, 535, "Amici"),
      new Manga(55, 536, "L'inferno gelato"),
      new Manga(55, 537, "Okama all'inferno"),
      new Manga(
        55,
        538,
        "Livello cinque virgola cinque= il nuovo regno okama"
      ),
      new Manga(55, 539, "Emporio= ormoni del vigore"),
      new Manga(55, 540, "Livello sei= l'inferno eterno"),
      new Manga(55, 541, "Come mai prima d'ora"),
      new Manga(56, 542, "Solo un altro incidente di cui raccontare"),
      new Manga(56, 543, "Cappello di paglia e Barbanera"),
      new Manga(56, 544, "Anche l'inferno chiude per ferie"),
      new Manga(
        56,
        545,
        "Verso il mondo esterno, dove splende il sole"
      ),
      new Manga(
        56,
        546,
        "Il capitano dei pirati uomini-pesce, Jimbe della flotta dei sette"
      ),
      new Manga(56, 547, "La grande fuga"),
      new Manga(56, 548, "Grazie"),
      new Manga(56, 549, "Rotta verso la battaglia"),
      new Manga(56, 550, "Il quartier generale della marina"),
      new Manga(56, 551, "L'imperatore Barbabianca"),
      new Manga(57, 552, "Ace e Barbabianca"),
      new Manga(57, 553, "La battaglia decisiva tra i più forti"),
      new Manga(57, 554, "L'ammiraglio akainu"),
      new Manga(57, 555, "Oars ed il suo cappello"),
      new Manga(57, 556, "La giustizia prevarrà!!"),
      new Manga(57, 557, "Rufy e Barbabianca"),
      new Manga(57, 558, "Fratellino"),
      new Manga(57, 559, "Destino"),
      new Manga(57, 560, "I prigionieri di impel down"),
      new Manga(57, 561, "Luffy vs Mihawk"),
      new Manga(57, 562, "Pirata vortice del ragno, Squardo"),
      new Manga(58, 563, "Un uomo, un cuore"),
      new Manga(58, 564, "L'uomo che fa tremare il mondo"),
      new Manga(58, 565, "Il sentiero di Oars"),
      new Manga(58, 566, "Assalto"),
      new Manga(
        58,
        567,
        "Marineford quartiere generale della marina, piazza Oris"
      ),
      new Manga(58, 568, "Fai come ti pare, paglia-chan"),
      new Manga(58, 569, "Mostro"),
      new Manga(58, 570, "Il ponte della vita"),
      new Manga(58, 571, "Patibolo"),
      new Manga(58, 572, "I tempi stanno cambiando"),
      new Manga(58, 573, "Questa era si chiama ''Barbabianca''"),
      new Manga(59, 574, "La morte di Portgas D. Ace"),
      new Manga(59, 575, "Neanche una parole, solo rabbia"),
      new Manga(59, 576, "Il grande pirata, Edward Newgate"),
      new Manga(59, 577, "Un grande evento dopo l'altro"),
      new Manga(59, 578, "Un regalo per la nuova era"),
      new Manga(59, 579, "Istanti di coraggio"),
      new Manga(59, 580, "La fine della guerra"),
      new Manga(59, 581, "Futuro strisciante"),
      new Manga(59, 582, "Rufy e Ace"),
      new Manga(59, 583, "Il capolinea dell'incertezza, Grey terminal"),
      new Manga(59, 584, "L'incidente Polchemy"),
      new Manga(60, 585, "Brindisi tra fratelli"),
      new Manga(60, 586, "Una fetida città"),
      new Manga(60, 587, "Io non scapperò"),
      new Manga(60, 588, "L'oceano di Sabo"),
      new Manga(60, 589, "Gli sforzi per arrivare alla gloria"),
      new Manga(60, 590, "Hey, fratellino"),
      new Manga(60, 591, "Sei sicuro che vada bene?"),
      new Manga(60, 592, "Gridare"),
      new Manga(60, 593, "News"),
      new Manga(60, 594, "Messaggio"),
      new Manga(61, 595, "Giuramento"),
      new Manga(61, 596, "Spectrum"),
      new Manga(61, 597, "3D2Y"),
      new Manga(61, 598, "Due anni dopo"),
      new Manga(61, 599, "I nove pirati"),
      new Manga(61, 600, "L'isola del nuovo inizio"),
      new Manga(61, 601, "Romance Dawn for the New World"),
      new Manga(61, 602, "Timone verso il basso"),
      new Manga(61, 603, "Conservatelo nel cuore"),
      new Manga(62, 604, "Negli abissi"),
      new Manga(62, 605, "Il kraken e i pirati"),
      new Manga(62, 606, "Avventura negli abissi"),
      new Manga(62, 607, "Diecimila metri sotto i mari"),
      new Manga(62, 608, "Il paradiso sommerso"),
      new Manga(62, 609, "Avventura nell'isola degli uomini-pesce"),
      new Manga(62, 610, "Madame Shirley l'indovina"),
      new Manga(62, 611, "Hody jones"),
      new Manga(
        62,
        612,
        "Accompagnati dallo squalo che avevamo salvato"
      ),
      new Manga(
        62,
        613,
        "La principessa sirena nella torre conchiglia"
      ),
      new Manga(62, 614, "Quel che è fatto è fatto"),
      new Manga(63, 615, "La maledizione target target"),
      new Manga(63, 616, "L'anniversario della vendetta"),
      new Manga(63, 617, "Scioccante incidente a colle corallo"),
      new Manga(63, 618, "Proposta di matrimonio"),
      new Manga(63, 619, "Alla foresta marina"),
      new Manga(63, 620, "Il parco divertimenti tanto anelato"),
      new Manga(63, 621, "Otohine e Tiger"),
      new Manga(63, 622, "I pirati del sole"),
      new Manga(63, 623, "Il pirata Fisher Tiger"),
      new Manga(63, 624, "La regina Otohine"),
      new Manga(63, 625, "Volontà senza eredi"),
      new Manga(63, 626, "I tre fratelli Nettuno"),
      new Manga(64, 627, "Te ne sono grato"),
      new Manga(64, 628, "Purificazione"),
      new Manga(64, 629, "L'ex-membro della flotta dei 7 non ci sta"),
      new Manga(64, 630, "A briglia sciolta"),
      new Manga(64, 631, "Place de la Gyoncorde"),
      new Manga(64, 632, "Lo sapevo già"),
      new Manga(64, 633, "Amico o nemico?"),
      new Manga(64, 634, "Dieci contro centomila"),
      new Manga(64, 635, "Cosi schifoso da metterti le ali ai piedi"),
      new Manga(64, 636, "Il generale del paese del futuro"),
      new Manga(65, 637, "L'antica arca"),
      new Manga(65, 638, "Scappahoshi"),
      new Manga(65, 639, "Proteggerò ogni cosa"),
      new Manga(65, 640, "Al di sopra dell'isola degli uomini-pesce"),
      new Manga(65, 641, "Che cosa sei, tu..?!"),
      new Manga(65, 642, "Perdere la faccia"),
      new Manga(65, 643, "Phantom"),
      new Manga(65, 644, "Da zero"),
      new Manga(65, 645, "Anche la morte è una vendetta"),
      new Manga(65, 646, "Rana"),
      new Manga(66, 647, "Ferma Noah!"),
      new Manga(
        66,
        648,
        "La strada che ci porterà a raggiungere il sole"
      ),
      new Manga(66, 649, "Danza di orate e di platesse"),
      new Manga(66, 650, "Due cambiamenti che dovreste sapere"),
      new Manga(66, 651, "Una voce dal Nuovo Mondo"),
      new Manga(66, 652, "Si prospettano tempi bui"),
      new Manga(66, 653, "Il cappello di un eroe"),
      new Manga(66, 654, "Gam (Piccolo Branco)"),
      new Manga(66, 655, "Punk Hazard"),
      new Manga(66, 656, "Avventura sull'isola in fiamme"),
      new Manga(67, 657, "Una testa mozzata"),
      new Manga(67, 658, "La stanza dei biscotti"),
      new Manga(67, 659, "A proposito del busto"),
      new Manga(67, 660, "Trafalgar Law, membro degli Shichibukai"),
      new Manga(67, 661, "E dal lago spuntano i predoni"),
      new Manga(
        67,
        662,
        "Law degli Shichibukai vs Vice Ammiraglio Smoker"
      ),
      new Manga(67, 663, "CC"),
      new Manga(67, 664, "Master Caesar Clown"),
      new Manga(67, 665, "Caramelle"),
      new Manga(67, 666, "Gli Yeti Cool Brothers"),
      new Manga(67, 667, "Cool Fight"),
      new Manga(68, 668, "Alleanza pirata"),
      new Manga(68, 669, "L'operazione ha inizio"),
      new Manga(68, 670, "Ghiaccio con una porzione di Slime"),
      new Manga(68, 671, "Gasu Gasu no mi"),
      new Manga(68, 672, "Il mio nome è Kinemon!!"),
      new Manga(68, 673, "Vergo e Joker"),
      new Manga(68, 674, "Spettatori"),
      new Manga(68, 675, "Il suo nome è ''Shinokuni''"),
      new Manga(68, 676, "L'arma di distruzione di massa perfetta"),
      new Manga(68, 677, "Counter Hazard!"),
      new Manga(68, 678, "Istituto di ricerca, lobby dell'edificio A"),
      new Manga(69, 679, "Lo spirito del G-5"),
      new Manga(
        69,
        680,
        "Il capo della base G5 della marina, vergo dal bambù brutale"
      ),
      new Manga(69, 681, "Rufy vs Master"),
      new Manga(69, 682, "Burattinaio"),
      new Manga(69, 683, "La donna di ghiaccio"),
      new Manga(69, 684, "Fermati, Vegapunk"),
      new Manga(69, 685, "Il mio nome è momonosuke!"),
      new Manga(69, 686, "La donna neve nella biscuits room"),
      new Manga(69, 687, "Animale selvaggio"),
      new Manga(69, 688, "Mocha"),
      new Manga(69, 689, "Un'isola che non esiste"),
      new Manga(69, 690, "SAD"),
      new Manga(70, 691, "Il re del paese della morte"),
      new Manga(70, 692, "Gli assassini di dressrosa"),
      new Manga(70, 693, "Muori per me"),
      new Manga(70, 694, "Un uomo molto pericoloso"),
      new Manga(70, 695, "Lasciateli a me!"),
      new Manga(70, 696, "Interessi comuni"),
      new Manga(70, 697, "Accordo"),
      new Manga(70, 698, "L'arrivo di Doflamingo"),
      new Manga(70, 699, "Edizione del mattino"),
      new Manga(70, 700, "Il suo gioco"),
      new Manga(
        71,
        701,
        "Avventura nella terra dell'amore, della passione e dei giocattoli"
      ),
      new Manga(71, 702, "Il colosseo della corrida"),
      new Manga(71, 703, "Sala d'attesa"),
      new Manga(71, 704, "Lucy e la statua di Kyros"),
      new Manga(71, 705, "Maynard l'inseguitore"),
      new Manga(71, 706, "Non riderò di te"),
      new Manga(71, 707, "Blocco B"),
      new Manga(71, 708, "Colosseo di canaglie"),
      new Manga(71, 709, "King Punch!!"),
      new Manga(71, 710, "Verso Green Bit"),
      new Manga(71, 711, "Avventura nella terra dei nani"),
      new Manga(72, 712, "Violet"),
      new Manga(72, 713, "Usoland"),
      new Manga(72, 714, "Lucy e Ucy"),
      new Manga(72, 715, "Battaglia serrata nel blocco C"),
      new Manga(72, 716, "Don Chinjao"),
      new Manga(72, 717, "Dimenticati da Dressrosa"),
      new Manga(72, 718, "L'esercito reale Riku ai campo di fiori"),
      new Manga(72, 719, "Apriti Chinjao"),
      new Manga(72, 720, "Gladiatori prigionieri"),
      new Manga(72, 721, "Rebecca ed il signor Soldatino"),
      new Manga(73, 722, "Stirpe reale"),
      new Manga(73, 723, "Cambiamento di piani"),
      new Manga(73, 724, "Il piano di Law"),
      new Manga(73, 725, "La donna imbattuta"),
      new Manga(73, 726, "La famiglia Riku"),
      new Manga(73, 727, "Un eroe che attende nell'ombra"),
      new Manga(73, 728, "Tutte queste tragedie"),
      new Manga(
        73,
        729,
        "Doflamingo della flotta dei 7 contro Law della flotta dei 7"
      ),
      new Manga(73, 730, "Tre Carte"),
      new Manga(73, 731, "Dressrosa Operazione S.O.P"),
      new Manga(74, 732, "Il Mondo Sotterraneo"),
      new Manga(74, 733, "A cosa ambisce Soldatino"),
      new Manga(74, 734, "Il turbine di Rommel"),
      new Manga(74, 735, "Le intenzioni di Fujitora"),
      new Manga(74, 736, "Il capo del personale esecutivo, Diamante"),
      new Manga(74, 737, "La torre del personale esecutivo"),
      new Manga(74, 738, "L'agente Sugar, dell'esercito di Trebol"),
      new Manga(74, 739, "Comandante"),
      new Manga(74, 740, "Per favore"),
      new Manga(74, 741, "Usoland il bugiardo"),
      new Manga(74, 742, "Ti sarò sempre accanto"),
      new Manga(75, 743, "Dressrosa in tumulto"),
      new Manga(75, 744, "Il generale Dell'Armata Rivoluzionaria"),
      new Manga(75, 745, "La gabbia per uccelli"),
      new Manga(75, 746, "Stelle"),
      new Manga(75, 747, "L'Agente d'elite, Pica"),
      new Manga(75, 748, "Restituire il favore"),
      new Manga(75, 749, "Avanzata! L'esercito dei piccoletti"),
      new Manga(
        75,
        750,
        "Riprende la battaglia! L'assalto a Dressrosa!"
      ),
      new Manga(75, 751, "Sabo contro l'Ammiraglio Fujitora"),
      new Manga(75, 752, "Palmo"),
      new Manga(76, 753, "Guerra"),
      new Manga(76, 754, "Lieto di fare la tua conoscenza"),
      new Manga(76, 755, "Un mondo al maschile"),
      new Manga(76, 756, "Il quarto livello"),
      new Manga(76, 757, "Asso nella manica"),
      new Manga(76, 758, "Ignoralo e va avanti"),
      new Manga(76, 759, "Piano segreto"),
      new Manga(76, 760, "La stessa scommessa"),
      new Manga(76, 761, "Il frutto Ope Ope"),
      new Manga(76, 762, "La città bianca"),
      new Manga(76, 763, "Dichiarazione di natura umana"),
      new Manga(77, 764, "Il mostro bianco"),
      new Manga(77, 765, "L'isola del destino, Minion"),
      new Manga(77, 766, "Smile"),
      new Manga(77, 767, "Cora-san"),
      new Manga(77, 768, "Quel grilletto, quel giorno..."),
      new Manga(77, 769, "Il pirata Bellamy"),
      new Manga(77, 770, "La lancia di Erbaf"),
      new Manga(77, 771, "Sai, il leader della marina happo"),
      new Manga(77, 772, "Cavolish e Barto"),
      new Manga(77, 773, "Metà e metà"),
      new Manga(77, 774, "Leo, il capo dei guerrieri Tontatta"),
      new Manga(77, 775, "Dare tutto il mio amore a Lucian"),
      new Manga(78, 776, "L'eroe del colosseo"),
      new Manga(78, 777, "Zoro vs Pica"),
      new Manga(78, 778, "Ipotesi numero 5"),
      new Manga(78, 779, "Lo scontro finale"),
      new Manga(78, 780, "La maledizione del cuore"),
      new Manga(78, 781, "Il desiderio tanto atteso"),
      new Manga(78, 782, "Il fascino del male"),
      new Manga(78, 783, "Intralciare la mia strada"),
      new Manga(78, 784, "Gear Fourth"),
      new Manga(78, 785, "Anche con le gambe spezzate"),
      new Manga(79, 786, "Gatz"),
      new Manga(79, 787, "4 minuti prima"),
      new Manga(79, 788, "La mia battaglia"),
      new Manga(79, 789, "Lucy"),
      new Manga(79, 790, "Cielo e Terra"),
      new Manga(79, 791, "Macerie"),
      new Manga(79, 792, "Inchino"),
      new Manga(79, 793, "La tigre e il cane"),
      new Manga(79, 794, "L'avventura di Sabo"),
      new Manga(79, 795, "Suicidio"),
      new Manga(80, 796, "La decisione del soldato"),
      new Manga(80, 797, "Rebecca"),
      new Manga(80, 798, "Cuore"),
      new Manga(80, 799, "Padre e figli"),
      new Manga(80, 800, "Scambiare le tazze di sake"),
      new Manga(80, 801, "Si alzi il sipario!"),
      new Manga(80, 802, "Zou"),
      new Manga(80, 803, "Scalando l'elefante"),
      new Manga(80, 804, "Avventura sul dorso dell'elefante"),
      new Manga(80, 805, "La razza dei visoni"),
      new Manga(80, 806, "Alla fortezza dell'addome destro"),
      new Manga(81, 807, "10 giorni prima"),
      new Manga(81, 808, "Il duca Canistrice"),
      new Manga(81, 809, "Il grande Gattovipera"),
      new Manga(
        81,
        810,
        "L'arrivo della ciurma di Sopracciglio di Paglia"
      ),
      new Manga(81, 811, "Roko"),
      new Manga(81, 812, "Capone ''Gang'' Bege"),
      new Manga(81, 813, "Un invito al Tea Party"),
      new Manga(81, 814, "Andiamo a incontrare il Grande Gattovipera!"),
      new Manga(81, 815, "Portami con te!"),
      new Manga(81, 816, "Cane contro Gatto"),
      new Manga(82, 817, "Raizo della nebbia"),
      new Manga(82, 818, "Dentro la balena"),
      new Manga(82, 819, "Momonosuke, erede del clan Kozuki"),
      new Manga(82, 820, "La storia di Cane e Gatto"),
      new Manga(82, 821, "Ricevuto"),
      new Manga(82, 822, "Scendendo dall'elefante"),
      new Manga(82, 823, "Un mondo vivace"),
      new Manga(82, 824, "Giochetti da pirata"),
      new Manga(82, 825, "La storia illustrata del ''We Times''"),
      new Manga(82, 826, "0 e 4"),
      new Manga(82, 827, "Totland"),
      new Manga(83, 828, "1 e 2"),
      new Manga(83, 829, "L'imperatrice Charlotte Linlin"),
      new Manga(83, 830, "L'uomo su cui scommettono tutti"),
      new Manga(83, 831, "Avventura nella foresta misteriosa"),
      new Manga(83, 832, "Regno Germa"),
      new Manga(83, 833, "Vinsmoke Judge"),
      new Manga(83, 834, "Il mio sogno"),
      new Manga(83, 835, "Il paese delle anime"),
      new Manga(83, 836, "La vivre card che mi ha dato Laura"),
      new Manga(83, 837, "Rufy vs il comandante Cracker"),
      new Manga(83, 838, "Fropper"),
      new Manga(
        84,
        839,
        "Grazie per tutto quello che hai fatto per me"
      ),
      new Manga(84, 840, "Maschera di ferro"),
      new Manga(84, 841, "Verso il Mare Orientale"),
      new Manga(84, 842, "Il potere di uno stomaco pieno"),
      new Manga(84, 843, "Vinsmoke Sanji"),
      new Manga(84, 844, "Rufy contro Sanji"),
      new Manga(84, 845, "L'esercito infuriato"),
      new Manga(84, 846, "La custodia di Tamago"),
      new Manga(84, 847, "Rufy e Big Mom"),
      new Manga(84, 848, "Addio"),
      new Manga(85, 849, "Fropper nel mondo specchio"),
      new Manga(85, 850, "Raggio di speranza"),
      new Manga(85, 851, "Mozzicone"),
      new Manga(85, 852, "Il fallimento del Germa"),
      new Manga(85, 853, "Non qui!"),
      new Manga(85, 854, "Che diavolo sto facendo?!"),
      new Manga(85, 855, "Grrrooowwwlll!"),
      new Manga(85, 856, "Bugiardo"),
      new Manga(85, 857, "Torre"),
      new Manga(85, 858, "L'incontro"),
      new Manga(86, 859, "Il piano di assassinio dell'imperatrice"),
      new Manga(86, 860, "Il party inizia alle 10"),
      new Manga(86, 861, "L'attore consumato"),
      new Manga(86, 862, "Un tipo intelligente"),
      new Manga(86, 863, "Il perfetto gentiluomo"),
      new Manga(
        86,
        864,
        "Il piano per il massacro della Famiglia Vinsmoke"
      ),
      new Manga(86, 865, "Ehy, madre"),
      new Manga(86, 866, "Nata per distruggere"),
      new Manga(86, 867, "Buon compleanno"),
      new Manga(86, 868, "KX Launcher"),
      new Manga(86, 869, "Sotto assedio"),
      new Manga(87, 870, "Commiato"),
      new Manga(87, 871, "Vai, Caesar!"),
      new Manga(87, 872, "Soffice e cremoso"),
      new Manga(87, 873, "Come dolci in trappola"),
      new Manga(87, 874, "King Baum"),
      new Manga(87, 875, "L'onore di una donna"),
      new Manga(87, 876, "Pudding appare per caso!"),
      new Manga(87, 877, "Non sono così dolce"),
      new Manga(
        87,
        878,
        "Tribù dei visoni, il capo dei guardiani Pedro"
      ),
      new Manga(
        87,
        879,
        "Katakuri, uno dei tre dolci comandanti di Big Mom"
      ),
      new Manga(88, 880, "Nessuna via di fuga"),
      new Manga(88, 881, "La stanza dell'onda"),
      new Manga(88, 882, "Oltre le aspettative di un imperatore"),
      new Manga(88, 883, "Merenda"),
      new Manga(88, 884, "Chi?"),
      new Manga(88, 885, "E' Brulee!"),
      new Manga(88, 886, "Queshto e' il mio modo di vivere!"),
      new Manga(
        88,
        887,
        "Da qualche parte, c'e' qualcuno che desidera la tua felicità"
      ),
      new Manga(88, 888, "Leone"),
      new Manga(88, 889, "Una mama mai vista prima"),
      new Manga(89, 890, "Big Mom sulla nave"),
      new Manga(89, 891, "Credono in me!"),
      new Manga(89, 892, "Riconoscere un nemico potente"),
      new Manga(
        89,
        893,
        "La trentaseiesima figlia della famiglia Charlotte, Flambe'"
      ),
      new Manga(89, 894, "Mezzanotte e cinque minuti"),
      new Manga(89, 895, "Il pirata Rufy contro il dolce comandante"),
      new Manga(89, 896, "L'ultima richiesta"),
      new Manga(89, 897, "Il piano di fuga da Cacao Island di Pekoms"),
      new Manga(89, 898, "Torneremo di sicuro"),
      new Manga(89, 899, "L'ultima resistenza"),
      new Manga(89, 900, "Musical dalla brutta fine"),
      new Manga(90, 901, "Anche se dovessi morire, non morire!"),
      new Manga(90, 902, "Titoli di coda"),
      new Manga(90, 903, "Il quinto imperatore"),
      new Manga(
        90,
        904,
        "L'arrivo dei comandanti dell'armata rivoluzionaria"
      ),
      new Manga(90, 905, "Un mondo meraviglioso"),
      new Manga(90, 906, "La terra santa Mary Geoise"),
      new Manga(90, 907, "Il trono vuoto"),
      new Manga(90, 908, "Inizia il Reverie"),
      new Manga(90, 909, "Seppuku"),
      new Manga(90, 910, "Verso il paese di Wa"),
      new Manga(
        91,
        911,
        "Una grande avventura nella terra dei samurai!"
      ),
      new Manga(91, 912, "Il Villaggio Amigasa"),
      new Manga(91, 913, "Tsuru ricambia il favore"),
      new Manga(91, 914, "Okobore, la città in rovina"),
      new Manga(91, 915, "Bakura Town"),
      new Manga(91, 916, "Un grande incontro di sumo nel paese di Wa"),
      new Manga(91, 917, "La nave tesoro delle provviste"),
      new Manga(91, 918, "Luffytaro ripaga il favore"),
      new Manga(91, 919, "Le rovine del castello di Oden"),
      new Manga(91, 920, "Amo Oden"),
      new Manga(91, 921, "Shutenmaru"),
      new Manga(
        92,
        922,
        "Governatore generale dei pirati delle cento bestie= Kaido"
      ),
      new Manga(92, 923, "L'imperatore Kaido contro Luffy"),
      new Manga(92, 924, "Ha"),
      new Manga(92, 925, "Il vuoto"),
      new Manga(92, 926, "La miniera dei prigionieri"),
      new Manga(92, 927, "O-Toko, la kamuro"),
      new Manga(92, 928, "La cortigiana Komurasaki entra in scena"),
      new Manga(92, 929, "Kurozumi Orochi, Shogun del paese di Wa"),
      new Manga(92, 930, "La città di Ebisu"),
      new Manga(92, 931, "O-Soba Mask"),
      new Manga(93, 932, "Lo Shogun e la Cortigiana"),
      new Manga(93, 933, "La pietà di un samurai"),
      new Manga(93, 934, "Hyogoro il fiore"),
      new Manga(93, 935, "Queen"),
      new Manga(93, 936, "Il gran torneo sumo inferno"),
      new Manga(93, 937, "Gyukimaru sul ponte Oihagi"),
      new Manga(93, 938, "Il segreto di una donna"),
      new Manga(
        93,
        939,
        "Gli artigli di un vecchio lupo sono sempre affilati"
      ),
      new Manga(93, 940, "La scintilla della rivolta"),
      new Manga(93, 941, "Il chiacchierone della città di Ebisu"),
      new Manga(93, 942, "Yasuie Shimotuski, il daimyo di Hakumai"),
      new Manga(94, 943, "Gli Smile"),
      new Manga(94, 944, "Compagno"),
      new Manga(94, 945, "O-Lin"),
      new Manga(94, 946, "Queen vs O-Lin"),
      new Manga(94, 947, "La scommessa di Queen"),
      new Manga(94, 948, "Arriva Kawamatsu il kappa"),
      new Manga(94, 949, "Mummia"),
      new Manga(94, 950, "I sogni dei guerrieri"),
      new Manga(94, 951, "Furia"),
      new Manga(94, 952, "Hiyori e Kawamatsu"),
      new Manga(94, 953, "La volpe dal singolo travestimento"),
      new Manga(95, 954, "Benzina sul fuoco"),
      new Manga(95, 955, "Enma"),
      new Manga(95, 956, "Big News"),
      new Manga(95, 957, "Ultimate"),
      new Manga(95, 958, "Il porto promesso"),
      new Manga(95, 959, "Samurai"),
      new Manga(95, 960, "Entra in scena Kozuki Oden"),
      new Manga(95, 961, "L'incidente dello spirito della montagna"),
      new Manga(95, 962, "Il Daimyo e i suoi vassalli"),
      new Manga(95, 963, "Diventare un samurai"),
      new Manga(95, 964, "L'avventura di Oden"),
      new Manga(96, 965, "La congiura del clan Kurozumi"),
      new Manga(96, 966, "Roger e Barbabianca"),
      new Manga(96, 967, "L'avventura di Roger"),
      new Manga(96, 968, "Il ritorno di Oden"),
      new Manga(96, 969, "Il lord tonto"),
      new Manga(96, 970, "Oden vs Kaido"),
      new Manga(96, 971, "Bolliti vivi"),
      new Manga(96, 972, "Io sono Oden! Nato per bollire!"),
      new Manga(96, 973, "Il clan Kozuki"),
      new Manga(96, 974, "Verso Onigashima!"),
      new Manga(97, 975, "Il piano di Kin'emon"),
      new Manga(97, 976, "Lasciate che mi presenti"),
      new Manga(97, 977, "La festa non inizia ora"),
      new Manga(97, 978, "Entrano in scena i sei volanti"),
      new Manga(97, 979, "Problemi familiari"),
      new Manga(97, 980, "Musica da combattimento"),
      new Manga(97, 981, "Scontro"),
      new Manga(97, 982, "Da ruffiano a ruffiano"),
      new Manga(97, 983, "Tuono"),
      new Manga(97, 984, "La mia bibbia"),
      new Manga(98, 985, "Il progetto nuova Onigashima"),
      new Manga(98, 986, "Il mio nome"),
      new Manga(98, 987, "La raffinata veste del vassallo"),
      new Manga(98, 988, "Scusate il ritardo"),
      new Manga(
        98,
        989,
        "Per qualche motivo, non mi sento come se stessimo perdendo!"
      ),
      new Manga(98, 990, "Agente solitario"),
      new Manga(98, 991, "Lasciaci morire!"),
      new Manga(98, 992, "Resti"),
      new Manga(98, 993, "Il sogno di Wano"),
      new Manga(98, 994, "Puoi chiamarmi Yamato"),
      new Manga(99, 995, "Il giuramento della Kunoichi"),
      new Manga(99, 996, "L'isola del più forte"),
      new Manga(99, 997, "Fiamme"),
      new Manga(99, 998, "Gli Zoan ancestrali"),
      new Manga(99, 999, "Il sake che ho distillato per bere con te"),
      new Manga(99, 1000, "Rufy ''Cappello di paglia''"),
      new Manga(
        99,
        1001,
        "La battaglia decisiva dei mostri di Onigashima"
      ),
      new Manga(99, 1002, "Imperatori vs nuova generazione"),
      new Manga(99, 1003, "La notte su una tavola di Go"),
      new Manga(99, 1004, "Kibi dango"),
      new Manga(100, 1005, "La bambina demoniaca"),
      new Manga(100, 1006, "L'onorevole ''Hyogoro dei fiori''"),
      new Manga(100, 1007, "Il signor Tanuki"),
      new Manga(
        100,
        1008,
        "Ashura Doji, capo dei banditi del monte atama"
      ),
      new Manga(100, 1009, "Inferno"),
      new Manga(100, 1010, "Tonalità del re conquistatore"),
      new Manga(100, 1011, "Il codice morale dei fagioli rossi"),
      new Manga(100, 1012, "Fremere"),
      new Manga(100, 1013, "Anarchy in the BM"),
      new Manga(100, 1014, "L'attorucolo di una vita intera"),
      new Manga(100, 1015, "Catene"),
      new Manga(101, 1016, "Qui parla Tama!"),
      new Manga(101, 1017, "Ordini"),
      new Manga(101, 1018, "Jinbe vs Who's Who"),
      new Manga(101, 1019, "Heliceratops"),
      new Manga(101, 1020, "Robin vs Black Maria"),
      new Manga(101, 1021, "Demonio"),
      new Manga(101, 1022, "Le stelle si prendono la scena!"),
      new Manga(101, 1023, "Due gocce d'acqua"),
      new Manga(101, 1024, "Un tale"),
      new Manga(101, 1025, "Draghi gemelli"),
      new Manga(102, 1026, "La resa dei conti"),
      new Manga(102, 1027, "Un problema oltre ogni immaginazione"),
      new Manga(102, 1028, "Brachioserperus"),
      new Manga(102, 1029, "La torre"),
      new Manga(102, 1030, "L'eco dell'impermanenza di tutte le cose"),
      new Manga(102, 1031, "Il guerriero della scienza"),
      new Manga(102, 1032, "La spada preferita di Oden"),
      new Manga(102, 1033, "Shimotsuki Kouzaburou"),
      new Manga(102, 1034, "Sanji vs. Queen"),
      new Manga(102, 1035, "Zoro vs. King"),
      new Manga(103, 1036, "Il bushido è la ricerca della morte"),
      new Manga(103, 1037, "Otto trigrammi, drago alcolizzato"),
      new Manga(103, 1038, "Kidd &amp, Law vs. Big Mom"),
      new Manga(103, 1039, "Ruolo di chiusura"),
      new Manga(
        103,
        1040,
        "Le ultime preghiere davanti a dei mocciosi"
      ),
      new Manga(103, 1041, "Komurasaki"),
      new Manga(103, 1042, "Forte non vuol dire vincitore"),
      new Manga(103, 1043, "Fino alla nostra morte!"),
      new Manga(103, 1044, "Il guerriero della liberazione"),
      new Manga(103, 1045, "Il livello successivo"),
      new Manga(103, 1046, "Raizo"),
      new Manga(104, 1047, "Il cielo della capitale"),
      new Manga(104, 1048, "Vent'anni"),
      new Manga(104, 1049, "Il mondo a cui aspirare"),
      new Manga(104, 1050, "Onore"),
      new Manga(104, 1051, "Kozuki Momonosuke, lo shogun di Wano"),
      new Manga(104, 1052, "Una nuova mattina"),
      new Manga(104, 1053, "I nuovi sovrani"),
      new Manga(104, 1054, "Imperatore fiammante"),
      new Manga(104, 1055, "La nuova era"),
      new Manga(105, 1056, "Cross Guild"),
      new Manga(105, 1057, "Fine"),
      new Manga(105, 1058, "Il nuovo sovrano"),
      new Manga(105, 1059, "Ciò che è accaduto al capitano Koby"),
      new Manga(105, 1060, "Il sogno di Rufy"),
      new Manga(105, 1061, "Egghead, l'isola del futuro"),
      new Manga(105, 1062, "Avventura nel paese della scienza"),
      new Manga(105, 1063, "Tutto ciò che resta della mia famiglia"),
      new Manga(105, 1064, "Egghead Labo Phase"),
      new Manga(105, 1065, "I sei Vegapunk"),
      new Manga(106, 1066, "La volontà di Ohara"),
      new Manga(106, 1067, "Punk Records"),
      new Manga(106, 1068, "Il sogno di un genio"),
      new Manga(106, 1069, "Tutto al mondo nasce dal desiderio"),
      new Manga(106, 1070, "Gli esseri umani più forti"),
      new Manga(106, 1071, "L'eroe va all'attacco"),
      new Manga(106, 1072, "Il peso dei ricordi"),
      new Manga(106, 1073, "Miss Buckingham Stussy"),
      new Manga(106, 1074, "Mark III"),
      new Manga(106, 1075, "Labo Phase Death Game"),
      new Manga(106, 1076, "Vecchi Amici"),
      new Manga(107, 1077, "Avresti dovuto accorgermene prima"),
      new Manga(107, 1078, "Limite di fuga"),
      new Manga(
        107,
        1079,
        "I pirati del rosso, membro dei quattro imperatori"
      ),
      new Manga(107, 1080, "L'eroe leggendario"),
      new Manga(
        107,
        1081,
        "Kuzan, Capitano della Decima Flotta dei Pirati di Barbanera"
      ),
      new Manga(107, 1082, "Andiamo a prendercelo!"),
      new Manga(107, 1083, "La verità su quel giorno"),
      new Manga(107, 1084, "Il tentato omicidio di un drago celeste"),
      new Manga(107, 1085, "La morte di Nefertari Cobra"),
      new Manga(107, 1086, "I cinque astri di saggezza"),
      new Manga(107, 1087, "Navi da boxe"),
      new Manga(107, 1088, "L'ultima lezione"),
      new Manga(108, 1089, "Sotto assedio"),
      new Manga(108, 1090, "Kizaru"),
      new Manga(108, 1091, "Sentomaru"),
      new Manga(
        108,
        1092,
        "L'irruzione di Orso ''Il Tiranno'' nella Terra Santa"
      ),
      new Manga(108, 1093, "Luffy vs Kizaru"),
      new Manga(
        108,
        1094,
        "Jaygarcia Saturn, la Divinità Guerriera della Difesa Scientifica"
      ),
      new Manga(108, 1095, "Un mondo in cui è meglio morire"),
      new Manga(108, 1096, "Orsacchiotto"),
      new Manga(108, 1097, "Jinney"),
      new Manga(108, 1098, "La nascita di Bonney"),
      new Manga(108, 1099, "Pacifista"),
      new Manga(108, 1100, "Grazie, Bonney"),
      new Manga(109, 1101, "A Bonney"),
      new Manga(109, 1102, "La vita di Orso"),
      new Manga(109, 1103, "Scusa, papà"),
      new Manga(109, 1104, "Grazie, papà"),
      new Manga(109, 1105, "L'apice dell'idiozia"),
      new Manga(109, 1106, "Al tuo fianco"),
      new Manga(109, 1107, "Ti stavo cercando!"),
      new Manga(109, 1108, "Mondo, mi ricevi?"),
      new Manga(109, 1109, "Intralcio"),
      new Manga(109, 1110, "La discesa degli astri"),
      new Manga(110, 1111, "Lo scudo del sole"),
      new Manga(110, 1112, "Hard Aspect"),
      new Manga(110, 1113, "Stalemate"),
      new Manga(110, 1114, "Le ali di Icaro"),
      new Manga(110, 1115, "Frammenti di continenti"),
      new Manga(110, 1116, "Conflitti"),
      new Manga(110, 1117, "Voi"),
      new Manga(110, 1118, "Più libera che mai"),
      new Manga(110, 1119, "Emeth"),
      new Manga(110, 1120, "Atlas"),
      new Manga(110, 1121, "Il fluire del tempo"),
      new Manga(111, 1122, "Quando verrà il momento"),
      new Manga(111, 1123, "Le due settimane di vuoto"),
      new Manga(111, 1124, "Un caro amico"),
      new Manga(111, 1125, "Come pensi di procedere?"),
      new Manga(111, 1126, "Risolvere la questione"),
      new Manga(111, 1127, "Avventura nel paese del mistero"),
      new Manga(111, 1128, "RPG"),
      new Manga(111, 1129, "Livdoll"),
      new Manga(111, 1130, "Il principe maledetto"),
      new Manga(111, 1131, "Loki dell'oltretomba"),
      new Manga(111, 1132, "Avventura ad Elbaph"),
      new Manga(111, 1133, "Conta solo che tu sia felice"),
      new Manga(112, 1134, "La biblioteca del gufo"),
      new Manga(112, 1135, "Le coppe della fratellanza"),
      new Manga(112, 1136, "Il regno che attende il sole"),
      new Manga(112, 1137, "Shamrock entra in scena"),
      new Manga(112, 1138, "L'Harley"),
      new Manga(112, 1139, "Il divoramontagne"),
      new Manga(112, 1140, "Scopper Gaban"),
      new Manga(112, 1141, "Le donne più vecchie di me"),
      new Manga(112, 1142, "Ciò che più mi spaventa"),
      new Manga(112, 1143, "I cavalieri degli dei"),
      new Manga(112, 1144, "L'ora dei guerrieri"),
      new Manga(
        113,
        1145,
        "L'incendio nel secondo distretto della forestale sull'ottava strada dell'albero"
      ),
      new Manga(113, 1146, "Nella quiete, il moto"),
      new Manga(113, 1147, "Ciò che più ci spaventa"),
      new Manga(113, 1148, "Ronja"),
      new Manga(113, 1149, "Un secondo"),
      new Manga(113, 1150, "Domi reversi"),
      new Manga(113, 1151, "E' tutto chiaro!!!"),
      new Manga(113, 1152, "Un giorno orribile"),
      new Manga(113, 1153, "La nascita di Loki"),
      new Manga(113, 1154, "Non riesco nemmeno a morire"),
      new Manga(113, 1155, "I pirati di Rocks"),
      new Manga(114, 1156, "Idol"),
      new Manga(114, 1157, "Il bar leggendario"),
      new Manga(114, 1158, "Rocks vs. Harald"),
      new Manga(114, 1159, "L'isola del destino"),
      new Manga(114, 1160, "L'incidente di God Valley"),
      new Manga(
        114,
        1161,
        "Una poesia d'amore scritta sotto una pioggia di frecce"
      ),
      new Manga(114, 1162, "G.V.B.R."),
      new Manga(114, 1163, "La promessa"),
      new Manga(114, 1164, "Il sangue dei Davy"),
      new Manga(114, 1165, "Eco"),
      new Manga(115, 1166, "Nuove storie"),
    ];
  }

  getVolume(volume) {
    return this.mangaArray.find((manga) => manga.Volume === volume);
  }

  getCapitolo(capitolo) {
    return this.mangaArray.find((manga) => manga.Capitolo === capitolo);
  }

getTitolo(volume, capitolo) {
  const manga = this.mangaArray.find(
    (m) => m.Volume == volume && m.Capitolo == capitolo
  );


  if (!manga) {
    // Nessun elemento trovato
    console.warn(`⚠️ Nessun titolo trovato per Volume ${volume}, Capitolo ${capitolo}`);
    return "Titolo non disponibile";
  }

  // Se esiste, restituisci il titolo
  return manga.Titolo && manga.Titolo.trim() !== ""
    ? manga.Titolo
    : "Titolo non disponibile";
}

getLast() {
  return this.mangaArray[this.mangaArray.length - 1];
};
}

