export class OnePieceManga {
  constructor(volume, capitolo, titolo) {
    this.Volume = volume;
    this.Capitolo = capitolo;
    this.Titolo = titolo;
  }
}

export class OnePieceMangaList {
  constructor(mangaArray) {
    this.mangaArray = [
      new OnePieceManga(1, 1, "Romance Dawn, l'alba di una grande avventura"),
      new OnePieceManga(1, 2, "Rufy, il ragazzo dal cappello di paglia"),
      new OnePieceManga(1, 3, "Ecco Zoro, il cacciatore di pirati"),
      new OnePieceManga(1, 4, "Il capitano di vascello morgan mano d'ascia"),
      new OnePieceManga(1, 5, "Il Re Dei Pirati e il Più Grande Spadaccino"),
      new OnePieceManga(1, 6, "Il primo compagno"),
      new OnePieceManga(1, 7, "Amici"),
      new OnePieceManga(1, 8, "Ecco Nami"),
      new OnePieceManga(2, 9, "Femme fatale"),
      new OnePieceManga(2, 10, "Incidente al bar"),
      new OnePieceManga(2, 11, "Fuga"),
      new OnePieceManga(2, 12, "Il Cane"),
      new OnePieceManga(2, 13, "Tesoro"),
      new OnePieceManga(2, 14, "Imprudente"),
      new OnePieceManga(2, 15, "Gong"),
      new OnePieceManga(2, 16, "Versus! I pirati di Buggy!"),
      new OnePieceManga(2, 17, "Livelli diversi"),
      new OnePieceManga(3, 18, "Il pirata buggy il clown"),
      new OnePieceManga(3, 19, "Il frutto del diavolo"),
      new OnePieceManga(3, 20, "La via del ladro"),
      new OnePieceManga(3, 21, "Il villaggio"),
      new OnePieceManga(3, 22, "Sei una strana bestia"),
      new OnePieceManga(3, 23, "Ecco capitan Usopp"),
      new OnePieceManga(3, 24, "Qualcosa che non posso rinnegare"),
      new OnePieceManga(3, 25, "800 bugie"),
      new OnePieceManga(3, 26, "Il piano di capitan kuro"),
      new OnePieceManga(4, 27, "Il piano"),
      new OnePieceManga(4, 28, "Luna crescente"),
      new OnePieceManga(4, 29, "La salita "),
      new OnePieceManga(4, 30, "Great!"),
      new OnePieceManga(4, 31, "Verità"),
      new OnePieceManga(4, 32, "Disastro"),
      new OnePieceManga(4, 33, "L'uomo silenzioso"),
      new OnePieceManga(4, 34, "Il maggiordomo Krahador"),
      new OnePieceManga(4, 35, "Una salita ostica"),
      new OnePieceManga(5, 36, "Inseguimento!"),
      new OnePieceManga(5, 37, "Il pirata kuro lo stratega"),
      new OnePieceManga(5, 38, "Pirati"),
      new OnePieceManga(5, 39, "Per chi suona la campana "),
      new OnePieceManga(5, 40, "La ciurma dei pirati di Usopp "),
      new OnePieceManga(5, 41, "Per mare"),
      new OnePieceManga(5, 42, "Yosaku e Johnny"),
      new OnePieceManga(5, 43, "Ecco Sanji"),
      new OnePieceManga(5, 44, "I tre cuochi"),
      new OnePieceManga(6, 45, "Prima della tempesta"),
      new OnePieceManga(6, 46, "Un ospite sgradito"),
      new OnePieceManga(6, 47, "L'ammiraglio della flotta pirata, don krieg"),
      new OnePieceManga(6, 48, "Lascia perdere quella rotta"),
      new OnePieceManga(6, 49, "Tempesta"),
      new OnePieceManga(6, 50, "Ognuno per la propria strada"),
      new OnePieceManga(6, 51, "Roronoa Zoro cade in mare"),
      new OnePieceManga(6, 52, "Giuramento"),
      new OnePieceManga(6, 53, "Sabagashira I"),
      new OnePieceManga(7, 54, "Pearl Titolo-san"),
      new OnePieceManga(7, 55, "Jungle blood"),
      new OnePieceManga(7, 56, "Non ci penso nemmeno"),
      new OnePieceManga(7, 57, "A causa dei sogni"),
      new OnePieceManga(7, 58, "Vecchio di merda"),
      new OnePieceManga(7, 59, "Debito"),
      new OnePieceManga(7, 60, "Tra giusto e sbagliato"),
      new OnePieceManga(7, 61, "Demone"),
      new OnePieceManga(7, 62, "MH"),
      new OnePieceManga(8, 63, "Io non morirò"),
      new OnePieceManga(8, 64, "Grande lancia da battaglia"),
      new OnePieceManga(8, 65, "Preparazione"),
      new OnePieceManga(8, 66, "La distruzione della lancia"),
      new OnePieceManga(8, 67, "La zuppa"),
      new OnePieceManga(8, 68, "La quarta persona"),
      new OnePieceManga(8, 69, "Arlong park"),
      new OnePieceManga(8, 70, "La grande avventura del prode Usopp"),
      new OnePieceManga(8, 71, "Il re di tutte le creature viventi"),
      new OnePieceManga(9, 72, "In base ai propri mezzi"),
      new OnePieceManga(9, 73, "Il mostro venuto dalla Grand Line"),
      new OnePieceManga(9, 74, "Affari"),
      new OnePieceManga(9, 75, "Carte nautiche e uomini-pesce"),
      new OnePieceManga(9, 76, "Io dormo"),
      new OnePieceManga(
        9,
        77,
        "Il primo passo verso la realizzazione del sogno"
      ),
      new OnePieceManga(9, 78, "Bellmère-san"),
      new OnePieceManga(9, 79, "Vivere"),
      new OnePieceManga(9, 80, "Un crimine è un crimine"),
      new OnePieceManga(9, 81, "Lacrime"),
      new OnePieceManga(10, 82, "Ok, let's stand up!"),
      new OnePieceManga(10, 83, "Rufy in back"),
      new OnePieceManga(10, 84, "Morto vivente"),
      new OnePieceManga(10, 85, "Santoryu vs Rokutoryu"),
      new OnePieceManga(10, 86, "Cavalleria vs karate Uomini-Pesce"),
      new OnePieceManga(10, 87, "è finita!"),
      new OnePieceManga(10, 88, "Morire!"),
      new OnePieceManga(10, 89, "Cambio"),
      new OnePieceManga(10, 90, "Cosa sai fare?!"),
      new OnePieceManga(11, 91, "Darts"),
      new OnePieceManga(11, 92, "Felicità"),
      new OnePieceManga(11, 93, "Sta crollando"),
      new OnePieceManga(11, 94, "La seconda persona"),
      new OnePieceManga(11, 95, "E la girandola gira"),
      new OnePieceManga(11, 96, "Il peggiore dell'est"),
      new OnePieceManga(11, 97, "Sandai kitetsu"),
      new OnePieceManga(11, 98, "Nuvole nere"),
      new OnePieceManga(11, 99, "La morte di Rufy"),
      new OnePieceManga(12, 100, "La leggenda ha inizio!"),
      new OnePieceManga(12, 101, "Reverse Mountain"),
      new OnePieceManga(12, 102, "Ecco la Grand Line"),
      new OnePieceManga(12, 103, "La balena"),
      new OnePieceManga(12, 104, "Il promontorio della promessa"),
      new OnePieceManga(12, 105, "Il log pose"),
      new OnePieceManga(12, 106, "La città dell'accoglienza"),
      new OnePieceManga(12, 107, "Lapidi e chiaro di luna"),
      new OnePieceManga(12, 108, "100 cacciatori di taglie"),
      new OnePieceManga(13, 109, "Responsabilità"),
      new OnePieceManga(13, 110, "La notte infinita"),
      new OnePieceManga(13, 111, "Un'organizzazione criminale segreta"),
      new OnePieceManga(13, 112, "Rufy vs Zoro"),
      new OnePieceManga(13, 113, "Andrà tutto bene"),
      new OnePieceManga(13, 114, "Rotta"),
      new OnePieceManga(13, 115, "Avventura a Little Garden"),
      new OnePieceManga(13, 116, "Immensi"),
      new OnePieceManga(13, 117, "Dorry e Brogy"),
      new OnePieceManga(14, 118, "Non siamo soli"),
      new OnePieceManga(14, 119, "Espediente"),
      new OnePieceManga(14, 120, "Le lacrime del demone rosso"),
      new OnePieceManga(14, 121, "Lo sapevo"),
      new OnePieceManga(14, 122, "I morti non servono a nulla"),
      new OnePieceManga(14, 123, "Rufy vs Mr.3"),
      new OnePieceManga(14, 124, "Questo tè è davvero delizioso"),
      new OnePieceManga(14, 125, "Candle champion"),
      new OnePieceManga(14, 126, "Istinto"),
      new OnePieceManga(15, 127, "Il lumacofono"),
      new OnePieceManga(15, 128, "Bandiera pirata"),
      new OnePieceManga(15, 129, "Tutta a dritta!"),
      new OnePieceManga(15, 130, "Alla massima velocità"),
      new OnePieceManga(15, 131, "''Blink'' wapol"),
      new OnePieceManga(15, 132, "Visto?"),
      new OnePieceManga(15, 133, "Avventura nel paese senza nome"),
      new OnePieceManga(15, 134, "La dottoressa Kureha"),
      new OnePieceManga(15, 135, "Lapahn"),
      new OnePieceManga(15, 136, "Un uomo chiamato dorton"),
      new OnePieceManga(16, 137, "La valanga"),
      new OnePieceManga(16, 138, "In cima"),
      new OnePieceManga(16, 139, "Ecco Tony Tony Chopper"),
      new OnePieceManga(16, 140, "Vita nel castello innevato"),
      new OnePieceManga(16, 141, "Medicastro"),
      new OnePieceManga(16, 142, "Il teschio ed il ciliegio"),
      new OnePieceManga(16, 143, "Inesperto"),
      new OnePieceManga(16, 144, "I racconti della neve"),
      new OnePieceManga(16, 145, "Volontà ereditata"),
      new OnePieceManga(17, 146, "Combattere per proteggere il regno"),
      new OnePieceManga(17, 147, "Bugia"),
      new OnePieceManga(17, 148, "Indistruttibile"),
      new OnePieceManga(17, 149, "Rumble"),
      new OnePieceManga(17, 150, "Il Royal Drum Crown 7-Shot Blinking Cannon"),
      new OnePieceManga(17, 151, "Il cielo di Drum"),
      new OnePieceManga(17, 152, "Luna piena"),
      new OnePieceManga(17, 153, "I ciliegi di Hiluluk"),
      new OnePieceManga(17, 154, "Verso Alabasta"),
      new OnePieceManga(17, 155, "Il pirata Sir Crocodile"),
      new OnePieceManga(18, 156, "Tempo di okama"),
      new OnePieceManga(18, 157, "Ecco Ace"),
      new OnePieceManga(18, 158, "Sbarco ad Alabasta"),
      new OnePieceManga(18, 159, "A presto"),
      new OnePieceManga(18, 160, "Spiders cafè, 8 in punto"),
      new OnePieceManga(18, 161, "Elumalu, la città verde"),
      new OnePieceManga(18, 162, "Avventura nel regno della sabbia"),
      new OnePieceManga(18, 163, "Yuba, la città dei ribelli"),
      new OnePieceManga(18, 164, "Ami questo paese?"),
      new OnePieceManga(18, 165, "Operazione Utopia"),
      new OnePieceManga(18, 166, "Rufy vs Bibi"),
      new OnePieceManga(19, 167, "Il campo di battaglia"),
      new OnePieceManga(19, 168, "Rainbase, la città dei sogni"),
      new OnePieceManga(19, 169, "Il più forte guerriero del regno"),
      new OnePieceManga(19, 170, "Si comincia"),
      new OnePieceManga(19, 171, "Kohza, il leader ribelle"),
      new OnePieceManga(19, 172, "Ribellione"),
      new OnePieceManga(19, 173, "Coccobanana"),
      new OnePieceManga(19, 174, "Mr. Prince"),
      new OnePieceManga(19, 175, "Libertà"),
      new OnePieceManga(19, 176, "Rush!"),
      new OnePieceManga(20, 177, "30 milioni vs 81 milioni"),
      new OnePieceManga(20, 178, "Livello Grand Line"),
      new OnePieceManga(20, 179, "La battaglia decisiva sarà al Alubarna"),
      new OnePieceManga(20, 180, "Gli animali del regno di Alabasta"),
      new OnePieceManga(
        20,
        181,
        "Lo stratagemma della squadra delle super anatre dal becco macchiato"
      ),
      new OnePieceManga(20, 182, "Urla di rabbia"),
      new OnePieceManga(20, 183, "Il comandante Karu"),
      new OnePieceManga(20, 184, "Via cumulo di terra numero 4"),
      new OnePieceManga(20, 185, "Wow... Buono a sapersi..."),
      new OnePieceManga(20, 186, "Four"),
      new OnePieceManga(21, 187, "Alla pari"),
      new OnePieceManga(21, 188, "Okama Kenpo"),
      new OnePieceManga(21, 189, "Two"),
      new OnePieceManga(21, 190, "Clima Tact"),
      new OnePieceManga(21, 191, "La donna che controlla il clima"),
      new OnePieceManga(21, 192, "Attenzione ai tornado"),
      new OnePieceManga(21, 193, "Utopia"),
      new OnePieceManga(21, 194, "Tagliare l'acciaio"),
      new OnePieceManga(21, 195, "Mr. Bushido"),
      new OnePieceManga(22, 196, "One"),
      new OnePieceManga(22, 197, "I leader"),
      new OnePieceManga(22, 198, "4=15 del pomeriggio"),
      new OnePieceManga(22, 199, "Speranza"),
      new OnePieceManga(22, 200, "Acqua Rufy"),
      new OnePieceManga(22, 201, "Nico Robin"),
      new OnePieceManga(22, 202, "La tomba reale"),
      new OnePieceManga(22, 203, "Puzza di coccodrillo"),
      new OnePieceManga(22, 204, "Sangue"),
      new OnePieceManga(22, 205, "La base segreta del clan della sabbia"),
      new OnePieceManga(23, 206, "Fuoco alle polveri"),
      new OnePieceManga(23, 207, "Incubo"),
      new OnePieceManga(23, 208, "La divinità protettrice"),
      new OnePieceManga(23, 209, "Ti supererò"),
      new OnePieceManga(23, 210, "Zero"),
      new OnePieceManga(23, 211, "Il re"),
      new OnePieceManga(23, 212, "Un po' di giustizia"),
      new OnePieceManga(23, 213, "VIP"),
      new OnePieceManga(23, 214, "Il piano per fuggire dal regno di sabbia"),
      new OnePieceManga(23, 215, "L'ultimo valzer"),
      new OnePieceManga(23, 216, "L'avventura di Bibi"),
      new OnePieceManga(24, 217, "Clandestino a bordo"),
      new OnePieceManga(24, 218, "Il motivo per cui il log pose è sferico"),
      new OnePieceManga(24, 219, "Masira, il re dei recuperi"),
      new OnePieceManga(24, 220, "Due passi sott'acqua"),
      new OnePieceManga(24, 221, "I mostri"),
      new OnePieceManga(24, 222, "Il grande rookie"),
      new OnePieceManga(
        24,
        223,
        "Giuro che non combatterò contro nessuno in questa città"
      ),
      new OnePieceManga(24, 224, "Vietato sognare"),
      new OnePieceManga(24, 225, "I sogni degli uomini"),
      new OnePieceManga(24, 226, "Shojo, il re delle esplorazioni sottomarine"),
      new OnePieceManga(25, 227, "Noland il bugiardo"),
      new OnePieceManga(
        25,
        228,
        "Montblanc Cricket, l'ultimo capo della coalizione della montagna delle scimmie"
      ),
      new OnePieceManga(25, 229, "Andiamo a mangiare"),
      new OnePieceManga(25, 230, "Alla ricerca del South Bird"),
      new OnePieceManga(25, 231, "Bellamy la iena"),
      new OnePieceManga(25, 232, "L'uomo da cento milioni"),
      new OnePieceManga(25, 233, "La massima autorità mondiale"),
      new OnePieceManga(25, 234, "Abbiate l'accortezza di non dimenticarlo"),
      new OnePieceManga(25, 235, "Knock Up Stream"),
      new OnePieceManga(25, 236, "La nave vola nel cielo"),
      new OnePieceManga(26, 237, "In cielo"),
      new OnePieceManga(26, 238, "La porta del paradiso"),
      new OnePieceManga(26, 239, "Angel Beach"),
      new OnePieceManga(26, 240, "L'energia dei dial"),
      new OnePieceManga(26, 241, "Il giudizio divino"),
      new OnePieceManga(26, 242, "Criminali di seconda classe"),
      new OnePieceManga(26, 243, "Le prove"),
      new OnePieceManga(26, 244, "S.O.S"),
      new OnePieceManga(26, 245, "Avventura sull'isola di Dio"),
      new OnePieceManga(
        26,
        246,
        "Satori, il sacerdote della foresta dei perduti"
      ),
      new OnePieceManga(27, 247, "La prova delle sfere"),
      new OnePieceManga(27, 248, "Ex Dio vs Sacerdote"),
      new OnePieceManga(27, 249, "Il villaggio nascosto fra le nuvole"),
      new OnePieceManga(27, 250, "Il drago di sfere"),
      new OnePieceManga(27, 251, "Preludio"),
      new OnePieceManga(27, 252, "Ricongiungimento"),
      new OnePieceManga(27, 253, "Vearth"),
      new OnePieceManga(27, 254, "Aubade"),
      new OnePieceManga(27, 255, "Il serpentone e il gruppo di ricerca"),
      new OnePieceManga(28, 256, "Wiper il demone combattente"),
      new OnePieceManga(28, 257, "Dial battle"),
      new OnePieceManga(28, 258, "Molteplici direzioni verso sud"),
      new OnePieceManga(28, 259, "Zoro il pirata vs Braham il guerriero"),
      new OnePieceManga(
        28,
        260,
        "Rufy il pirata vs Wiper il demone combattente"
      ),
      new OnePieceManga(
        28,
        261,
        "Gembo il guerriero vs Yama, il comandante della Guardia Sacra"
      ),
      new OnePieceManga(28, 262, "Chopper il pirata vs Gedatsu il sacerdote"),
      new OnePieceManga(
        28,
        263,
        "Nami la pirata e lo strano cavaliere vs i Vice Comandanti dell'Armata sacra"
      ),
      new OnePieceManga(28, 264, "Kamakiri il guerriero vs Dio Ener"),
      new OnePieceManga(
        29,
        265,
        "Robin la piratessa vs Yama, il comandante della guardia sacra"
      ),
      new OnePieceManga(29, 266, "Chopper il pirata vs Ohm il sacerdote"),
      new OnePieceManga(29, 267, "Marcia"),
      new OnePieceManga(29, 268, "Suite"),
      new OnePieceManga(29, 269, "Concerto"),
      new OnePieceManga(29, 270, "Serenata"),
      new OnePieceManga(29, 271, "Zoro il pirata vs Ohm il sacerdote"),
      new OnePieceManga(29, 272, "Play"),
      new OnePieceManga(29, 273, "Quintetto"),
      new OnePieceManga(29, 274, "Oratorio"),
      new OnePieceManga(29, 275, "Divina Commedia"),
      new OnePieceManga(30, 276, "Shandia Rhythm"),
      new OnePieceManga(30, 277, "Maxim"),
      new OnePieceManga(30, 278, "Konis"),
      new OnePieceManga(30, 279, "Rufy il Pirata vs Dio Ener"),
      new OnePieceManga(30, 280, "Emersione"),
      new OnePieceManga(30, 281, "Deathpiea"),
      new OnePieceManga(30, 282, "Desiderio"),
      new OnePieceManga(
        30,
        283,
        "In prima linea nel salvataggio in nome dell'amore"
      ),
      new OnePieceManga(30, 284, "Ti ringrazio"),
      new OnePieceManga(30, 285, "Capriccio"),
      new OnePieceManga(31, 286, "Il demone di Shandora"),
      new OnePieceManga(31, 287, "Deicidio"),
      new OnePieceManga(31, 288, "Maledizione"),
      new OnePieceManga(31, 289, "Plenilunio"),
      new OnePieceManga(31, 290, "La luce di Shandora"),
      new OnePieceManga(31, 291, "Noi siamo qui"),
      new OnePieceManga(31, 292, "Incontrando una mezzaluna tra le nuvole"),
      new OnePieceManga(31, 293, "Bolero"),
      new OnePieceManga(31, 294, "Raigo"),
      new OnePieceManga(31, 295, "Giant Jack"),
      new OnePieceManga(32, 296, "Situazione ad alta quota"),
      new OnePieceManga(32, 297, "Preghiere da terra"),
      new OnePieceManga(32, 298, "Canto d'amore"),
      new OnePieceManga(32, 299, "Fantasia"),
      new OnePieceManga(32, 300, "Sinfonia"),
      new OnePieceManga(32, 301, "Sono stato qui"),
      new OnePieceManga(32, 302, "Finale"),
      new OnePieceManga(32, 303, "I pirati ricchi sfondati"),
      new OnePieceManga(32, 304, "Avventura sull'isola lunga"),
      new OnePieceManga(32, 305, "Foxy la volpe argentata"),
      new OnePieceManga(33, 306, "Donut race"),
      new OnePieceManga(33, 307, "Pronti, partenza... donut!"),
      new OnePieceManga(33, 308, "Battaglia d'interferenze"),
      new OnePieceManga(33, 309, "Groggy monsters"),
      new OnePieceManga(33, 310, "Groggy ring"),
      new OnePieceManga(33, 311, "Gioco duro"),
      new OnePieceManga(33, 312, "Goal!"),
      new OnePieceManga(33, 313, "L'evento principale"),
      new OnePieceManga(33, 314, "Combattimento!"),
      new OnePieceManga(33, 315, "La stanza segreta"),
      new OnePieceManga(33, 316, "Anima fraterna"),
      new OnePieceManga(34, 317, "K.O."),
      new OnePieceManga(34, 318, "Fine dei giochi"),
      new OnePieceManga(
        34,
        319,
        "L'ammiraglio Aokiji del quartier generale della marina"
      ),
      new OnePieceManga(34, 320, "Un potere straordinario"),
      new OnePieceManga(34, 321, "Da uomo a uomo"),
      new OnePieceManga(34, 322, "Puffing Tom"),
      new OnePieceManga(34, 323, "Water Seven la città dell'acqua"),
      new OnePieceManga(34, 324, "Avventura nella città d'acqua"),
      new OnePieceManga(34, 325, "Franky Family"),
      new OnePieceManga(34, 326, "Iceburg-san"),
      new OnePieceManga(34, 327, "Il Dock 1 dell'isola dei cantieri navali"),
      new OnePieceManga(35, 328, "L'incidente del sequestro del pirata"),
      new OnePieceManga(35, 329, "Il mio nome è Franky"),
      new OnePieceManga(35, 330, "Ho deciso!"),
      new OnePieceManga(35, 331, "Un grande litigio"),
      new OnePieceManga(35, 332, "Rufy vs Usop"),
      new OnePieceManga(35, 333, "Capitano"),
      new OnePieceManga(35, 334, "L'incidente della stanza chiusa a chiave"),
      new OnePieceManga(35, 335, "Avvertimento"),
      new OnePieceManga(35, 336, "Rufy vs Franky"),
      new OnePieceManga(36, 337, "I guardiani della città dell'acqua"),
      new OnePieceManga(36, 338, "Coup de vent"),
      new OnePieceManga(36, 339, "Qualche chiacchiera"),
      new OnePieceManga(36, 340, "La donna portatrice di sventura"),
      new OnePieceManga(36, 341, "Diavolo"),
      new OnePieceManga(36, 342, "I messaggeri dell'oscurità"),
      new OnePieceManga(36, 343, "Chiper Pol N°9"),
      new OnePieceManga(36, 344, "Potere contrapposto"),
      new OnePieceManga(36, 345, "Gli infiltrati"),
      new OnePieceManga(36, 346, "La nona giustizia"),
      new OnePieceManga(37, 347, "Rokushiki"),
      new OnePieceManga(37, 348, "Forza combattiva"),
      new OnePieceManga(37, 349, "Comune cittadino"),
      new OnePieceManga(37, 350, "Il magazzino sotto il ponte"),
      new OnePieceManga(37, 351, "Klabautermann"),
      new OnePieceManga(37, 352, "Tom's Workers"),
      new OnePieceManga(37, 353, "Il leggendario carpentiere"),
      new OnePieceManga(37, 354, "Il Treno marino"),
      new OnePieceManga(37, 355, "Spandam"),
      new OnePieceManga(37, 356, "Tom-san"),
      new OnePieceManga(37, 357, "Cutty Flam"),
      new OnePieceManga(38, 358, "Resurrezione"),
      new OnePieceManga(38, 359, "Bingo"),
      new OnePieceManga(38, 360, "Partenza imminente"),
      new OnePieceManga(38, 361, "P.S."),
      new OnePieceManga(38, 362, "Riflusso di marea"),
      new OnePieceManga(38, 363, "Acqua laguna"),
      new OnePieceManga(38, 364, "Kokoro"),
      new OnePieceManga(38, 365, "Rocketman!"),
      new OnePieceManga(38, 366, "Si va in scena"),
      new OnePieceManga(38, 367, "Sogeking"),
      new OnePieceManga(39, 368, "Battaglia a bordo del treno marino"),
      new OnePieceManga(39, 369, "Ramen Kenpo"),
      new OnePieceManga(39, 370, "Non sei sola"),
      new OnePieceManga(39, 371, "L'ammirevole capitano T-Bone"),
      new OnePieceManga(39, 372, "Parage"),
      new OnePieceManga(39, 373, "Male necessario"),
      new OnePieceManga(39, 374, "Lotta"),
      new OnePieceManga(39, 375, "I superuomini di Enies Lobby"),
      new OnePieceManga(39, 376, "Ho capito!"),
      new OnePieceManga(
        39,
        377,
        "La grande battaglia decisiva sull'isola giudiziaria"
      ),
      new OnePieceManga(40, 378, "Il bilancio delle perdite"),
      new OnePieceManga(40, 379, "Doriki"),
      new OnePieceManga(
        40,
        380,
        "Espresso per l'isola principale di Enies Lobby"
      ),
      new OnePieceManga(40, 381, "Licenziati"),
      new OnePieceManga(40, 382, "Il covo dei demoni"),
      new OnePieceManga(40, 383, "Rufy vs Blueno"),
      new OnePieceManga(40, 384, "L'ora del contrattacco"),
      new OnePieceManga(40, 385, "C'è solo un modo"),
      new OnePieceManga(40, 386, "Senza precedenti"),
      new OnePieceManga(40, 387, "Gear"),
      new OnePieceManga(40, 388, "Gear Second"),
      new OnePieceManga(41, 389, "Risposta"),
      new OnePieceManga(41, 390, "Contrattacco"),
      new OnePieceManga(41, 391, "La bambina chiamata mostro"),
      new OnePieceManga(41, 392, "Dereshi"),
      new OnePieceManga(41, 393, "Olvia"),
      new OnePieceManga(41, 394, "I demoni di Ohara"),
      new OnePieceManga(41, 395, "Ohara vs governo mondiale"),
      new OnePieceManga(41, 396, "Saul"),
      new OnePieceManga(41, 397, "Raggiungere il futuro"),
      new OnePieceManga(41, 398, "Dichiarazione di guerra"),
      new OnePieceManga(41, 399, "Saltate nella cascata!!"),
      new OnePieceManga(42, 400, "La chiave della libertà"),
      new OnePieceManga(42, 401, "Pirati vs CP9"),
      new OnePieceManga(42, 402, "Le manette numero 2"),
      new OnePieceManga(42, 403, "Mister cavalleria"),
      new OnePieceManga(42, 404, "Franky vs Fukuro"),
      new OnePieceManga(42, 405, "Potere"),
      new OnePieceManga(42, 406, "Seimei Kikan"),
      new OnePieceManga(42, 407, "Mostro"),
      new OnePieceManga(42, 408, "Il mostro vs Kumadori"),
      new OnePieceManga(
        42,
        409,
        "Cattive notizie dalla trasmissione d'emergenza"
      ),
      new OnePieceManga(43, 410, "La Nami gigantesca"),
      new OnePieceManga(43, 411, "Nami vs Califa"),
      new OnePieceManga(43, 412, "Occasione persa"),
      new OnePieceManga(43, 413, "Il cacciatore"),
      new OnePieceManga(43, 414, "Sanji vs Jabura"),
      new OnePieceManga(43, 415, "Heat up!"),
      new OnePieceManga(43, 416, "Zoro vs Kaku"),
      new OnePieceManga(43, 417, "Ashura"),
      new OnePieceManga(43, 418, "Rufy vs Rob Lucci"),
      new OnePieceManga(43, 419, "La leggenda dell'eroe"),
      new OnePieceManga(44, 420, "Buster Call"),
      new OnePieceManga(44, 421, "Gear Third"),
      new OnePieceManga(44, 422, "Rob Lucci"),
      new OnePieceManga(44, 423, "La leggenda della sirena"),
      new OnePieceManga(44, 424, "Nave per la fuga"),
      new OnePieceManga(44, 425, "Combattimento disperato sul ponte"),
      new OnePieceManga(44, 426, "Nave in attesa del vento"),
      new OnePieceManga(44, 427, "Qui non siamo affatto all'inferno!"),
      new OnePieceManga(44, 428, "Torniamo indietro!"),
      new OnePieceManga(44, 429, "Disfatta totale"),
      new OnePieceManga(44, 430, "Cade una soffice neve di ricordi"),
      new OnePieceManga(45, 431, "L'amorevole pugno"),
      new OnePieceManga(45, 432, "Scatola a sorpresa"),
      new OnePieceManga(45, 433, "Il nome di quel mare è..."),
      new OnePieceManga(45, 434, "Barbabianca e il Rosso"),
      new OnePieceManga(45, 435, "Capiamo ciò che provate..."),
      new OnePieceManga(45, 436, "Pants from Frankyhouse"),
      new OnePieceManga(45, 437, "Nudo, ma uomo vero"),
      new OnePieceManga(45, 438, "Orgoglio"),
      new OnePieceManga(45, 439, "Il terzo e il settimo"),
      new OnePieceManga(45, 440, "Pugno di fuoco vs Barbanera"),
      new OnePieceManga(46, 441, "Duello sull'isola di Banaro"),
      new OnePieceManga(46, 442, "Avventura nelle acque malefiche"),
      new OnePieceManga(46, 443, "Thriller Bark"),
      new OnePieceManga(46, 444, "Avventura sull'isola fantasma"),
      new OnePieceManga(46, 445, "The Zombie"),
      new OnePieceManga(46, 446, "Il dottor Hogback"),
      new OnePieceManga(46, 447, "Gli Zombie a sorpresa"),
      new OnePieceManga(46, 448, "Moria"),
      new OnePieceManga(46, 449, "I quattro mostri di Thriller Bark"),
      new OnePieceManga(47, 450, "General Zombie Night"),
      new OnePieceManga(47, 451, "Il wonder garden di Perona!"),
      new OnePieceManga(47, 452, "Jigoro del vento"),
      new OnePieceManga(
        47,
        453,
        "Cielo coperto con probabili precipitazioni di ossa"
      ),
      new OnePieceManga(47, 454, "Canterino"),
      new OnePieceManga(47, 455, "Gekko Moria della flotta dei sette"),
      new OnePieceManga(47, 456, "Il demone giunto dal regno dei ghiacci"),
      new OnePieceManga(47, 457, "Caaarneee!"),
      new OnePieceManga(47, 458, "Tutto ma non l'afro!"),
      new OnePieceManga(
        47,
        459,
        "Non potrei mai dire= ''Scusa tanto, ma siamo morti''"
      ),
      new OnePieceManga(48, 460, "Recuperarle prima che sorga il sole!"),
      new OnePieceManga(48, 461, "Ghost Buster"),
      new OnePieceManga(48, 462, "L'avventura di Oz"),
      new OnePieceManga(48, 463, "Sanji il pirata vs absolom il misterioso"),
      new OnePieceManga(48, 464, "Il sogno di Sanji"),
      new OnePieceManga(48, 465, "Il pirata Usopp vs la principessa Perona"),
      new OnePieceManga(48, 466, "Concluso"),
      new OnePieceManga(48, 467, "Zoro il pirata vs Ryuma il samurai"),
      new OnePieceManga(48, 468, "Chopper il pirata vs lo spettrale Hogback"),
      new OnePieceManga(48, 469, "Venite fuori Mugiwara!!!"),
      new OnePieceManga(48, 470, "Oz vs Mugiwara"),
      new OnePieceManga(49, 471, "My friend"),
      new OnePieceManga(49, 472, "Down"),
      new OnePieceManga(49, 473, "Bartolomew Kuma della flotta dei sette"),
      new OnePieceManga(49, 474, "Non ci resta che farlo!"),
      new OnePieceManga(49, 475, "I pirati della foresta"),
      new OnePieceManga(49, 476, "Nightmare Rufy"),
      new OnePieceManga(49, 477, "3/8"),
      new OnePieceManga(49, 478, "Rufy vs Rufy"),
      new OnePieceManga(49, 479, "Guerriero della speranza"),
      new OnePieceManga(49, 480, "Intercettamento"),
      new OnePieceManga(49, 481, "Shadow's Asgard"),
      new OnePieceManga(50, 482, "Arriva l'alba"),
      new OnePieceManga(50, 483, "Fine di un sogno"),
      new OnePieceManga(50, 484, "Boing"),
      new OnePieceManga(
        50,
        485,
        "Equipaggio di Cappello di Paglia= Zoro il cacciatore di pirati"
      ),
      new OnePieceManga(50, 486, "Pianoforte"),
      new OnePieceManga(50, 487, "Quella canzone"),
      new OnePieceManga(50, 488, "La canzone della vita"),
      new OnePieceManga(50, 489, "L'ottava persona"),
      new OnePieceManga(50, 490, "Ancora li!"),
      new OnePieceManga(50, 491, "I piloti dei pesci volanti"),
      new OnePieceManga(51, 492, "Duval dalla maschera di ferro"),
      new OnePieceManga(51, 493, "Mi conosci"),
      new OnePieceManga(51, 494, "La tragedia di Duval"),
      new OnePieceManga(51, 495, "Il Cannone Gaon"),
      new OnePieceManga(51, 496, "La Mangrovia Yarukiman"),
      new OnePieceManga(51, 497, "Avventura nell'isola delle bolle danzanti"),
      new OnePieceManga(51, 498, "Le undici Supernove"),
      new OnePieceManga(51, 499, "Sabaody Park"),
      new OnePieceManga(51, 500, "Fuoco sotto la cenere della storia"),
      new OnePieceManga(51, 501, "Il mondo inizia a ribollire"),
      new OnePieceManga(51, 502, "L'incidente dei dragoviani"),
      new OnePieceManga(52, 503, "Un'isola nel caos"),
      new OnePieceManga(52, 504, "Pirati in prima linea all'attacco!!"),
      new OnePieceManga(52, 505, "Orso"),
      new OnePieceManga(52, 506, "Roger e Rayleigh"),
      new OnePieceManga(52, 507, "Lo sbarco di Kizaru"),
      new OnePieceManga(52, 508, "L'isola del massacro"),
      new OnePieceManga(52, 509, "Kizaru contro 4 capitani"),
      new OnePieceManga(
        52,
        510,
        "La squadra di Cappello di Paglia contro la macchina da guerra"
      ),
      new OnePieceManga(52, 511, "Sentomaru e la sua ascia"),
      new OnePieceManga(52, 512, "La scomparsa di Zoro"),
      new OnePieceManga(53, 513, "Non ho potuto nemmeno..."),
      new OnePieceManga(53, 514, "Funghi che crescono sul corpo"),
      new OnePieceManga(53, 515, "Avventura nell'isola delle donne"),
      new OnePieceManga(53, 516, "L'imperatrice pirata, Boa Hancock"),
      new OnePieceManga(53, 517, "Il bagno"),
      new OnePieceManga(53, 518, "L'arena"),
      new OnePieceManga(53, 519, "L'indole di un re"),
      new OnePieceManga(53, 520, "L'occhio della Gorgone"),
      new OnePieceManga(
        53,
        521,
        "L'artiglio dei draghi che si ergono nei cieli"
      ),
      new OnePieceManga(53, 522, "Malattia mortale"),
      new OnePieceManga(54, 523, "Inferno"),
      new OnePieceManga(54, 524, "Nessuno può fermarci adesso"),
      new OnePieceManga(54, 525, "Impel Down, la prigione subacquea"),
      new OnePieceManga(54, 526, "Avventura nella grande prigione"),
      new OnePieceManga(54, 527, "Lv.1, l'inferno purpureo"),
      new OnePieceManga(54, 528, "Jinbe, il cavaliere dei mari"),
      new OnePieceManga(54, 529, "L'inferno delle bestie"),
      new OnePieceManga(54, 530, "Da un inferno all'altro"),
      new OnePieceManga(54, 531, "L'inferno dell'inedia"),
      new OnePieceManga(54, 532, "Minotauro, la guardia demoniaca"),
      new OnePieceManga(55, 533, "Livello quattro= l'inferno bollente"),
      new OnePieceManga(55, 534, "Capo guardiano magellan vs il pirata"),
      new OnePieceManga(55, 535, "Amici"),
      new OnePieceManga(55, 536, "L'inferno gelato"),
      new OnePieceManga(55, 537, "Okama all'inferno"),
      new OnePieceManga(
        55,
        538,
        "Livello cinque virgola cinque= il nuovo regno okama"
      ),
      new OnePieceManga(55, 539, "Emporio= ormoni del vigore"),
      new OnePieceManga(55, 540, "Livello sei= l'inferno eterno"),
      new OnePieceManga(55, 541, "Come mai prima d'ora"),
      new OnePieceManga(56, 542, "Solo un altro incidente di cui raccontare"),
      new OnePieceManga(56, 543, "Cappello di paglia e Barbanera"),
      new OnePieceManga(56, 544, "Anche l'inferno chiude per ferie"),
      new OnePieceManga(
        56,
        545,
        "Verso il mondo esterno, dove splende il sole"
      ),
      new OnePieceManga(
        56,
        546,
        "Il capitano dei pirati uomini-pesce, Jimbe della flotta dei sette"
      ),
      new OnePieceManga(56, 547, "La grande fuga"),
      new OnePieceManga(56, 548, "Grazie"),
      new OnePieceManga(56, 549, "Rotta verso la battaglia"),
      new OnePieceManga(56, 550, "Il quartier generale della marina"),
      new OnePieceManga(56, 551, "L'imperatore Barbabianca"),
      new OnePieceManga(57, 552, "Ace e Barbabianca"),
      new OnePieceManga(57, 553, "La battaglia decisiva tra i più forti"),
      new OnePieceManga(57, 554, "L'ammiraglio akainu"),
      new OnePieceManga(57, 555, "Oars ed il suo cappello"),
      new OnePieceManga(57, 556, "La giustizia prevarrà!!"),
      new OnePieceManga(57, 557, "Rufy e Barbabianca"),
      new OnePieceManga(57, 558, "Fratellino"),
      new OnePieceManga(57, 559, "Destino"),
      new OnePieceManga(57, 560, "I prigionieri di impel down"),
      new OnePieceManga(57, 561, "Luffy vs Mihawk"),
      new OnePieceManga(57, 562, "Pirata vortice del ragno, Squardo"),
      new OnePieceManga(58, 563, "Un uomo, un cuore"),
      new OnePieceManga(58, 564, "L'uomo che fa tremare il mondo"),
      new OnePieceManga(58, 565, "Il sentiero di Oars"),
      new OnePieceManga(58, 566, "Assalto"),
      new OnePieceManga(
        58,
        567,
        "Marineford quartiere generale della marina, piazza Oris"
      ),
      new OnePieceManga(58, 568, "Fai come ti pare, paglia-chan"),
      new OnePieceManga(58, 569, "Mostro"),
      new OnePieceManga(58, 570, "Il ponte della vita"),
      new OnePieceManga(58, 571, "Patibolo"),
      new OnePieceManga(58, 572, "I tempi stanno cambiando"),
      new OnePieceManga(58, 573, "Questa era si chiama ''Barbabianca''"),
      new OnePieceManga(59, 574, "La morte di Portgas D. Ace"),
      new OnePieceManga(59, 575, "Neanche una parole, solo rabbia"),
      new OnePieceManga(59, 576, "Il grande pirata, Edward Newgate"),
      new OnePieceManga(59, 577, "Un grande evento dopo l'altro"),
      new OnePieceManga(59, 578, "Un regalo per la nuova era"),
      new OnePieceManga(59, 579, "Istanti di coraggio"),
      new OnePieceManga(59, 580, "La fine della guerra"),
      new OnePieceManga(59, 581, "Futuro strisciante"),
      new OnePieceManga(59, 582, "Rufy e Ace"),
      new OnePieceManga(59, 583, "Il capolinea dell'incertezza, Grey terminal"),
      new OnePieceManga(59, 584, "L'incidente Polchemy"),
      new OnePieceManga(60, 585, "Brindisi tra fratelli"),
      new OnePieceManga(60, 586, "Una fetida città"),
      new OnePieceManga(60, 587, "Io non scapperò"),
      new OnePieceManga(60, 588, "L'oceano di Sabo"),
      new OnePieceManga(60, 589, "Gli sforzi per arrivare alla gloria"),
      new OnePieceManga(60, 590, "Hey, fratellino"),
      new OnePieceManga(60, 591, "Sei sicuro che vada bene?"),
      new OnePieceManga(60, 592, "Gridare"),
      new OnePieceManga(60, 593, "News"),
      new OnePieceManga(60, 594, "Messaggio"),
      new OnePieceManga(61, 595, "Giuramento"),
      new OnePieceManga(61, 596, "Spectrum"),
      new OnePieceManga(61, 597, "3D2Y"),
      new OnePieceManga(61, 598, "Due anni dopo"),
      new OnePieceManga(61, 599, "I nove pirati"),
      new OnePieceManga(61, 600, "L'isola del nuovo inizio"),
      new OnePieceManga(61, 601, "Romance Dawn for the New World"),
      new OnePieceManga(61, 602, "Timone verso il basso"),
      new OnePieceManga(61, 603, "Conservatelo nel cuore"),
      new OnePieceManga(62, 604, "Negli abissi"),
      new OnePieceManga(62, 605, "Il kraken e i pirati"),
      new OnePieceManga(62, 606, "Avventura negli abissi"),
      new OnePieceManga(62, 607, "Diecimila metri sotto i mari"),
      new OnePieceManga(62, 608, "Il paradiso sommerso"),
      new OnePieceManga(62, 609, "Avventura nell'isola degli uomini-pesce"),
      new OnePieceManga(62, 610, "Madame Shirley l'indovina"),
      new OnePieceManga(62, 611, "Hody jones"),
      new OnePieceManga(
        62,
        612,
        "Accompagnati dallo squalo che avevamo salvato"
      ),
      new OnePieceManga(
        62,
        613,
        "La principessa sirena nella torre conchiglia"
      ),
      new OnePieceManga(62, 614, "Quel che è fatto è fatto"),
      new OnePieceManga(63, 615, "La maledizione target target"),
      new OnePieceManga(63, 616, "L'anniversario della vendetta"),
      new OnePieceManga(63, 617, "Scioccante incidente a colle corallo"),
      new OnePieceManga(63, 618, "Proposta di matrimonio"),
      new OnePieceManga(63, 619, "Alla foresta marina"),
      new OnePieceManga(63, 620, "Il parco divertimenti tanto anelato"),
      new OnePieceManga(63, 621, "Otohine e Tiger"),
      new OnePieceManga(63, 622, "I pirati del sole"),
      new OnePieceManga(63, 623, "Il pirata Fisher Tiger"),
      new OnePieceManga(63, 624, "La regina Otohine"),
      new OnePieceManga(63, 625, "Volontà senza eredi"),
      new OnePieceManga(63, 626, "I tre fratelli Nettuno"),
      new OnePieceManga(64, 627, "Te ne sono grato"),
      new OnePieceManga(64, 628, "Purificazione"),
      new OnePieceManga(64, 629, "L'ex-membro della flotta dei 7 non ci sta"),
      new OnePieceManga(64, 630, "A briglia sciolta"),
      new OnePieceManga(64, 631, "Place de la Gyoncorde"),
      new OnePieceManga(64, 632, "Lo sapevo già"),
      new OnePieceManga(64, 633, "Amico o nemico?"),
      new OnePieceManga(64, 634, "Dieci contro centomila"),
      new OnePieceManga(64, 635, "Cosi schifoso da metterti le ali ai piedi"),
      new OnePieceManga(64, 636, "Il generale del paese del futuro"),
      new OnePieceManga(65, 637, "L'antica arca"),
      new OnePieceManga(65, 638, "Scappahoshi"),
      new OnePieceManga(65, 639, "Proteggerò ogni cosa"),
      new OnePieceManga(65, 640, "Al di sopra dell'isola degli uomini-pesce"),
      new OnePieceManga(65, 641, "Che cosa sei, tu..?!"),
      new OnePieceManga(65, 642, "Perdere la faccia"),
      new OnePieceManga(65, 643, "Phantom"),
      new OnePieceManga(65, 644, "Da zero"),
      new OnePieceManga(65, 645, "Anche la morte è una vendetta"),
      new OnePieceManga(65, 646, "Rana"),
      new OnePieceManga(66, 647, "Ferma Noah!"),
      new OnePieceManga(
        66,
        648,
        "La strada che ci porterà a raggiungere il sole"
      ),
      new OnePieceManga(66, 649, "Danza di orate e di platesse"),
      new OnePieceManga(66, 650, "Due cambiamenti che dovreste sapere"),
      new OnePieceManga(66, 651, "Una voce dal Nuovo Mondo"),
      new OnePieceManga(66, 652, "Si prospettano tempi bui"),
      new OnePieceManga(66, 653, "Il cappello di un eroe"),
      new OnePieceManga(66, 654, "Gam (Piccolo Branco)"),
      new OnePieceManga(66, 655, "Punk Hazard"),
      new OnePieceManga(66, 656, "Avventura sull'isola in fiamme"),
      new OnePieceManga(67, 657, "Una testa mozzata"),
      new OnePieceManga(67, 658, "La stanza dei biscotti"),
      new OnePieceManga(67, 659, "A proposito del busto"),
      new OnePieceManga(67, 660, "Trafalgar Law, membro degli Shichibukai"),
      new OnePieceManga(67, 661, "E dal lago spuntano i predoni"),
      new OnePieceManga(
        67,
        662,
        "Law degli Shichibukai vs Vice Ammiraglio Smoker"
      ),
      new OnePieceManga(67, 663, "CC"),
      new OnePieceManga(67, 664, "Master Caesar Clown"),
      new OnePieceManga(67, 665, "Caramelle"),
      new OnePieceManga(67, 666, "Gli Yeti Cool Brothers"),
      new OnePieceManga(67, 667, "Cool Fight"),
      new OnePieceManga(68, 668, "Alleanza pirata"),
      new OnePieceManga(68, 669, "L'operazione ha inizio"),
      new OnePieceManga(68, 670, "Ghiaccio con una porzione di Slime"),
      new OnePieceManga(68, 671, "Gasu Gasu no mi"),
      new OnePieceManga(68, 672, "Il mio nome è Kinemon!!"),
      new OnePieceManga(68, 673, "Vergo e Joker"),
      new OnePieceManga(68, 674, "Spettatori"),
      new OnePieceManga(68, 675, "Il suo nome è ''Shinokuni''"),
      new OnePieceManga(68, 676, "L'arma di distruzione di massa perfetta"),
      new OnePieceManga(68, 677, "Counter Hazard!"),
      new OnePieceManga(68, 678, "Istituto di ricerca, lobby dell'edificio A"),
      new OnePieceManga(69, 679, "Lo spirito del G-5"),
      new OnePieceManga(
        69,
        680,
        "Il capo della base G5 della marina, vergo dal bambù brutale"
      ),
      new OnePieceManga(69, 681, "Rufy vs Master"),
      new OnePieceManga(69, 682, "Burattinaio"),
      new OnePieceManga(69, 683, "La donna di ghiaccio"),
      new OnePieceManga(69, 684, "Fermati, Vegapunk"),
      new OnePieceManga(69, 685, "Il mio nome è momonosuke!"),
      new OnePieceManga(69, 686, "La donna neve nella biscuits room"),
      new OnePieceManga(69, 687, "Animale selvaggio"),
      new OnePieceManga(69, 688, "Mocha"),
      new OnePieceManga(69, 689, "Un'isola che non esiste"),
      new OnePieceManga(69, 690, "SAD"),
      new OnePieceManga(70, 691, "Il re del paese della morte"),
      new OnePieceManga(70, 692, "Gli assassini di dressrosa"),
      new OnePieceManga(70, 693, "Muori per me"),
      new OnePieceManga(70, 694, "Un uomo molto pericoloso"),
      new OnePieceManga(70, 695, "Lasciateli a me!"),
      new OnePieceManga(70, 696, "Interessi comuni"),
      new OnePieceManga(70, 697, "Accordo"),
      new OnePieceManga(70, 698, "L'arrivo di Doflamingo"),
      new OnePieceManga(70, 699, "Edizione del mattino"),
      new OnePieceManga(70, 700, "Il suo gioco"),
      new OnePieceManga(
        71,
        701,
        "Avventura nella terra dell'amore, della passione e dei giocattoli"
      ),
      new OnePieceManga(71, 702, "Il colosseo della corrida"),
      new OnePieceManga(71, 703, "Sala d'attesa"),
      new OnePieceManga(71, 704, "Lucy e la statua di Kyros"),
      new OnePieceManga(71, 705, "Maynard l'inseguitore"),
      new OnePieceManga(71, 706, "Non riderò di te"),
      new OnePieceManga(71, 707, "Blocco B"),
      new OnePieceManga(71, 708, "Colosseo di canaglie"),
      new OnePieceManga(71, 709, "King Punch!!"),
      new OnePieceManga(71, 710, "Verso Green Bit"),
      new OnePieceManga(71, 711, "Avventura nella terra dei nani"),
      new OnePieceManga(72, 712, "Violet"),
      new OnePieceManga(72, 713, "Usoland"),
      new OnePieceManga(72, 714, "Lucy e Ucy"),
      new OnePieceManga(72, 715, "Battaglia serrata nel blocco C"),
      new OnePieceManga(72, 716, "Don Chinjao"),
      new OnePieceManga(72, 717, "Dimenticati da Dressrosa"),
      new OnePieceManga(72, 718, "L'esercito reale Riku ai campo di fiori"),
      new OnePieceManga(72, 719, "Apriti Chinjao"),
      new OnePieceManga(72, 720, "Gladiatori prigionieri"),
      new OnePieceManga(72, 721, "Rebecca ed il signor Soldatino"),
      new OnePieceManga(73, 722, "Stirpe reale"),
      new OnePieceManga(73, 723, "Cambiamento di piani"),
      new OnePieceManga(73, 724, "Il piano di Law"),
      new OnePieceManga(73, 725, "La donna imbattuta"),
      new OnePieceManga(73, 726, "La famiglia Riku"),
      new OnePieceManga(73, 727, "Un eroe che attende nell'ombra"),
      new OnePieceManga(73, 728, "Tutte queste tragedie"),
      new OnePieceManga(
        73,
        729,
        "Doflamingo della flotta dei 7 contro Law della flotta dei 7"
      ),
      new OnePieceManga(73, 730, "Tre Carte"),
      new OnePieceManga(73, 731, "Dressrosa Operazione S.O.P"),
      new OnePieceManga(74, 732, "Il Mondo Sotterraneo"),
      new OnePieceManga(74, 733, "A cosa ambisce Soldatino"),
      new OnePieceManga(74, 734, "Il turbine di Rommel"),
      new OnePieceManga(74, 735, "Le intenzioni di Fujitora"),
      new OnePieceManga(74, 736, "Il capo del personale esecutivo, Diamante"),
      new OnePieceManga(74, 737, "La torre del personale esecutivo"),
      new OnePieceManga(74, 738, "L'agente Sugar, dell'esercito di Trebol"),
      new OnePieceManga(74, 739, "Comandante"),
      new OnePieceManga(74, 740, "Per favore"),
      new OnePieceManga(74, 741, "Usoland il bugiardo"),
      new OnePieceManga(74, 742, "Ti sarò sempre accanto"),
      new OnePieceManga(75, 743, "Dressrosa in tumulto"),
      new OnePieceManga(75, 744, "Il generale Dell'Armata Rivoluzionaria"),
      new OnePieceManga(75, 745, "La gabbia per uccelli"),
      new OnePieceManga(75, 746, "Stelle"),
      new OnePieceManga(75, 747, "L'Agente d'elite, Pica"),
      new OnePieceManga(75, 748, "Restituire il favore"),
      new OnePieceManga(75, 749, "Avanzata! L'esercito dei piccoletti"),
      new OnePieceManga(
        75,
        750,
        "Riprende la battaglia! L'assalto a Dressrosa!"
      ),
      new OnePieceManga(75, 751, "Sabo contro l'Ammiraglio Fujitora"),
      new OnePieceManga(75, 752, "Palmo"),
      new OnePieceManga(76, 753, "Guerra"),
      new OnePieceManga(76, 754, "Lieto di fare la tua conoscenza"),
      new OnePieceManga(76, 755, "Un mondo al maschile"),
      new OnePieceManga(76, 756, "Il quarto livello"),
      new OnePieceManga(76, 757, "Asso nella manica"),
      new OnePieceManga(76, 758, "Ignoralo e va avanti"),
      new OnePieceManga(76, 759, "Piano segreto"),
      new OnePieceManga(76, 760, "La stessa scommessa"),
      new OnePieceManga(76, 761, "Il frutto Ope Ope"),
      new OnePieceManga(76, 762, "La città bianca"),
      new OnePieceManga(76, 763, "Dichiarazione di natura umana"),
      new OnePieceManga(77, 764, "Il mostro bianco"),
      new OnePieceManga(77, 765, "L'isola del destino, Minion"),
      new OnePieceManga(77, 766, "Smile"),
      new OnePieceManga(77, 767, "Cora-san"),
      new OnePieceManga(77, 768, "Quel grilletto, quel giorno..."),
      new OnePieceManga(77, 769, "Il pirata Bellamy"),
      new OnePieceManga(77, 770, "La lancia di Erbaf"),
      new OnePieceManga(77, 771, "Sai, il leader della marina happo"),
      new OnePieceManga(77, 772, "Cavolish e Barto"),
      new OnePieceManga(77, 773, "Metà e metà"),
      new OnePieceManga(77, 774, "Leo, il capo dei guerrieri Tontatta"),
      new OnePieceManga(77, 775, "Dare tutto il mio amore a Lucian"),
      new OnePieceManga(78, 776, "L'eroe del colosseo"),
      new OnePieceManga(78, 777, "Zoro vs Pica"),
      new OnePieceManga(78, 778, "Ipotesi numero 5"),
      new OnePieceManga(78, 779, "Lo scontro finale"),
      new OnePieceManga(78, 780, "La maledizione del cuore"),
      new OnePieceManga(78, 781, "Il desiderio tanto atteso"),
      new OnePieceManga(78, 782, "Il fascino del male"),
      new OnePieceManga(78, 783, "Intralciare la mia strada"),
      new OnePieceManga(78, 784, "Gear Fourth"),
      new OnePieceManga(78, 785, "Anche con le gambe spezzate"),
      new OnePieceManga(79, 786, "Gatz"),
      new OnePieceManga(79, 787, "4 minuti prima"),
      new OnePieceManga(79, 788, "La mia battaglia"),
      new OnePieceManga(79, 789, "Lucy"),
      new OnePieceManga(79, 790, "Cielo e Terra"),
      new OnePieceManga(79, 791, "Macerie"),
      new OnePieceManga(79, 792, "Inchino"),
      new OnePieceManga(79, 793, "La tigre e il cane"),
      new OnePieceManga(79, 794, "L'avventura di Sabo"),
      new OnePieceManga(79, 795, "Suicidio"),
      new OnePieceManga(80, 796, "La decisione del soldato"),
      new OnePieceManga(80, 797, "Rebecca"),
      new OnePieceManga(80, 798, "Cuore"),
      new OnePieceManga(80, 799, "Padre e figli"),
      new OnePieceManga(80, 800, "Scambiare le tazze di sake"),
      new OnePieceManga(80, 801, "Si alzi il sipario!"),
      new OnePieceManga(80, 802, "Zou"),
      new OnePieceManga(80, 803, "Scalando l'elefante"),
      new OnePieceManga(80, 804, "Avventura sul dorso dell'elefante"),
      new OnePieceManga(80, 805, "La razza dei visoni"),
      new OnePieceManga(80, 806, "Alla fortezza dell'addome destro"),
      new OnePieceManga(81, 807, "10 giorni prima"),
      new OnePieceManga(81, 808, "Il duca Canistrice"),
      new OnePieceManga(81, 809, "Il grande Gattovipera"),
      new OnePieceManga(
        81,
        810,
        "L'arrivo della ciurma di Sopracciglio di Paglia"
      ),
      new OnePieceManga(81, 811, "Roko"),
      new OnePieceManga(81, 812, "Capone ''Gang'' Bege"),
      new OnePieceManga(81, 813, "Un invito al Tea Party"),
      new OnePieceManga(81, 814, "Andiamo a incontrare il Grande Gattovipera!"),
      new OnePieceManga(81, 815, "Portami con te!"),
      new OnePieceManga(81, 816, "Cane contro Gatto"),
      new OnePieceManga(82, 817, "Raizo della nebbia"),
      new OnePieceManga(82, 818, "Dentro la balena"),
      new OnePieceManga(82, 819, "Momonosuke, erede del clan Kozuki"),
      new OnePieceManga(82, 820, "La storia di Cane e Gatto"),
      new OnePieceManga(82, 821, "Ricevuto"),
      new OnePieceManga(82, 822, "Scendendo dall'elefante"),
      new OnePieceManga(82, 823, "Un mondo vivace"),
      new OnePieceManga(82, 824, "Giochetti da pirata"),
      new OnePieceManga(82, 825, "La storia illustrata del ''We Times''"),
      new OnePieceManga(82, 826, "0 e 4"),
      new OnePieceManga(82, 827, "Totland"),
      new OnePieceManga(83, 828, "1 e 2"),
      new OnePieceManga(83, 829, "L'imperatrice Charlotte Linlin"),
      new OnePieceManga(83, 830, "L'uomo su cui scommettono tutti"),
      new OnePieceManga(83, 831, "Avventura nella foresta misteriosa"),
      new OnePieceManga(83, 832, "Regno Germa"),
      new OnePieceManga(83, 833, "Vinsmoke Judge"),
      new OnePieceManga(83, 834, "Il mio sogno"),
      new OnePieceManga(83, 835, "Il paese delle anime"),
      new OnePieceManga(83, 836, "La vivre card che mi ha dato Laura"),
      new OnePieceManga(83, 837, "Rufy vs il comandante Cracker"),
      new OnePieceManga(83, 838, "Fropper"),
      new OnePieceManga(
        84,
        839,
        "Grazie per tutto quello che hai fatto per me"
      ),
      new OnePieceManga(84, 840, "Maschera di ferro"),
      new OnePieceManga(84, 841, "Verso il Mare Orientale"),
      new OnePieceManga(84, 842, "Il potere di uno stomaco pieno"),
      new OnePieceManga(84, 843, "Vinsmoke Sanji"),
      new OnePieceManga(84, 844, "Rufy contro Sanji"),
      new OnePieceManga(84, 845, "L'esercito infuriato"),
      new OnePieceManga(84, 846, "La custodia di Tamago"),
      new OnePieceManga(84, 847, "Rufy e Big Mom"),
      new OnePieceManga(84, 848, "Addio"),
      new OnePieceManga(85, 849, "Fropper nel mondo specchio"),
      new OnePieceManga(85, 850, "Raggio di speranza"),
      new OnePieceManga(85, 851, "Mozzicone"),
      new OnePieceManga(85, 852, "Il fallimento del Germa"),
      new OnePieceManga(85, 853, "Non qui!"),
      new OnePieceManga(85, 854, "Che diavolo sto facendo?!"),
      new OnePieceManga(85, 855, "Grrrooowwwlll!"),
      new OnePieceManga(85, 856, "Bugiardo"),
      new OnePieceManga(85, 857, "Torre"),
      new OnePieceManga(85, 858, "L'incontro"),
      new OnePieceManga(86, 859, "Il piano di assassinio dell'imperatrice"),
      new OnePieceManga(86, 860, "Il party inizia alle 10"),
      new OnePieceManga(86, 861, "L'attore consumato"),
      new OnePieceManga(86, 862, "Un tipo intelligente"),
      new OnePieceManga(86, 863, "Il perfetto gentiluomo"),
      new OnePieceManga(
        86,
        864,
        "Il piano per il massacro della Famiglia Vinsmoke"
      ),
      new OnePieceManga(86, 865, "Ehy, madre"),
      new OnePieceManga(86, 866, "Nata per distruggere"),
      new OnePieceManga(86, 867, "Buon compleanno"),
      new OnePieceManga(86, 868, "KX Launcher"),
      new OnePieceManga(86, 869, "Sotto assedio"),
      new OnePieceManga(87, 870, "Commiato"),
      new OnePieceManga(87, 871, "Vai, Caesar!"),
      new OnePieceManga(87, 872, "Soffice e cremoso"),
      new OnePieceManga(87, 873, "Come dolci in trappola"),
      new OnePieceManga(87, 874, "King Baum"),
      new OnePieceManga(87, 875, "L'onore di una donna"),
      new OnePieceManga(87, 876, "Pudding appare per caso!"),
      new OnePieceManga(87, 877, "Non sono così dolce"),
      new OnePieceManga(
        87,
        878,
        "Tribù dei visoni, il capo dei guardiani Pedro"
      ),
      new OnePieceManga(
        87,
        879,
        "Katakuri, uno dei tre dolci comandanti di Big Mom"
      ),
      new OnePieceManga(88, 880, "Nessuna via di fuga"),
      new OnePieceManga(88, 881, "La stanza dell'onda"),
      new OnePieceManga(88, 882, "Oltre le aspettative di un imperatore"),
      new OnePieceManga(88, 883, "Merenda"),
      new OnePieceManga(88, 884, "Chi?"),
      new OnePieceManga(88, 885, "E' Brulee!"),
      new OnePieceManga(88, 886, "Queshto e' il mio modo di vivere!"),
      new OnePieceManga(
        88,
        887,
        "Da qualche parte, c'e' qualcuno che desidera la tua felicità"
      ),
      new OnePieceManga(88, 888, "Leone"),
      new OnePieceManga(88, 889, "Una mama mai vista prima"),
      new OnePieceManga(89, 890, "Big Mom sulla nave"),
      new OnePieceManga(89, 891, "Credono in me!"),
      new OnePieceManga(89, 892, "Riconoscere un nemico potente"),
      new OnePieceManga(
        89,
        893,
        "La trentaseiesima figlia della famiglia Charlotte, Flambe'"
      ),
      new OnePieceManga(89, 894, "Mezzanotte e cinque minuti"),
      new OnePieceManga(89, 895, "Il pirata Rufy contro il dolce comandante"),
      new OnePieceManga(89, 896, "L'ultima richiesta"),
      new OnePieceManga(89, 897, "Il piano di fuga da Cacao Island di Pekoms"),
      new OnePieceManga(89, 898, "Torneremo di sicuro"),
      new OnePieceManga(89, 899, "L'ultima resistenza"),
      new OnePieceManga(89, 900, "Musical dalla brutta fine"),
      new OnePieceManga(90, 901, "Anche se dovessi morire, non morire!"),
      new OnePieceManga(90, 902, "Titoli di coda"),
      new OnePieceManga(90, 903, "Il quinto imperatore"),
      new OnePieceManga(
        90,
        904,
        "L'arrivo dei comandanti dell'armata rivoluzionaria"
      ),
      new OnePieceManga(90, 905, "Un mondo meraviglioso"),
      new OnePieceManga(90, 906, "La terra santa Mary Geoise"),
      new OnePieceManga(90, 907, "Il trono vuoto"),
      new OnePieceManga(90, 908, "Inizia il Reverie"),
      new OnePieceManga(90, 909, "Seppuku"),
      new OnePieceManga(90, 910, "Verso il paese di Wa"),
      new OnePieceManga(
        91,
        911,
        "Una grande avventura nella terra dei samurai!"
      ),
      new OnePieceManga(91, 912, "Il Villaggio Amigasa"),
      new OnePieceManga(91, 913, "Tsuru ricambia il favore"),
      new OnePieceManga(91, 914, "Okobore, la città in rovina"),
      new OnePieceManga(91, 915, "Bakura Town"),
      new OnePieceManga(91, 916, "Un grande incontro di sumo nel paese di Wa"),
      new OnePieceManga(91, 917, "La nave tesoro delle provviste"),
      new OnePieceManga(91, 918, "Luffytaro ripaga il favore"),
      new OnePieceManga(91, 919, "Le rovine del castello di Oden"),
      new OnePieceManga(91, 920, "Amo Oden"),
      new OnePieceManga(91, 921, "Shutenmaru"),
      new OnePieceManga(
        92,
        922,
        "Governatore generale dei pirati delle cento bestie= Kaido"
      ),
      new OnePieceManga(92, 923, "L'imperatore Kaido contro Luffy"),
      new OnePieceManga(92, 924, "Ha"),
      new OnePieceManga(92, 925, "Il vuoto"),
      new OnePieceManga(92, 926, "La miniera dei prigionieri"),
      new OnePieceManga(92, 927, "O-Toko, la kamuro"),
      new OnePieceManga(92, 928, "La cortigiana Komurasaki entra in scena"),
      new OnePieceManga(92, 929, "Kurozumi Orochi, Shogun del paese di Wa"),
      new OnePieceManga(92, 930, "La città di Ebisu"),
      new OnePieceManga(92, 931, "O-Soba Mask"),
      new OnePieceManga(93, 932, "Lo Shogun e la Cortigiana"),
      new OnePieceManga(93, 933, "La pietà di un samurai"),
      new OnePieceManga(93, 934, "Hyogoro il fiore"),
      new OnePieceManga(93, 935, "Queen"),
      new OnePieceManga(93, 936, "Il gran torneo sumo inferno"),
      new OnePieceManga(93, 937, "Gyukimaru sul ponte Oihagi"),
      new OnePieceManga(93, 938, "Il segreto di una donna"),
      new OnePieceManga(
        93,
        939,
        "Gli artigli di un vecchio lupo sono sempre affilati"
      ),
      new OnePieceManga(93, 940, "La scintilla della rivolta"),
      new OnePieceManga(93, 941, "Il chiacchierone della città di Ebisu"),
      new OnePieceManga(93, 942, "Yasuie Shimotuski, il daimyo di Hakumai"),
      new OnePieceManga(94, 943, "Gli Smile"),
      new OnePieceManga(94, 944, "Compagno"),
      new OnePieceManga(94, 945, "O-Lin"),
      new OnePieceManga(94, 946, "Queen vs O-Lin"),
      new OnePieceManga(94, 947, "La scommessa di Queen"),
      new OnePieceManga(94, 948, "Arriva Kawamatsu il kappa"),
      new OnePieceManga(94, 949, "Mummia"),
      new OnePieceManga(94, 950, "I sogni dei guerrieri"),
      new OnePieceManga(94, 951, "Furia"),
      new OnePieceManga(94, 952, "Hiyori e Kawamatsu"),
      new OnePieceManga(94, 953, "La volpe dal singolo travestimento"),
      new OnePieceManga(95, 954, "Benzina sul fuoco"),
      new OnePieceManga(95, 955, "Enma"),
      new OnePieceManga(95, 956, "Big News"),
      new OnePieceManga(95, 957, "Ultimate"),
      new OnePieceManga(95, 958, "Il porto promesso"),
      new OnePieceManga(95, 959, "Samurai"),
      new OnePieceManga(95, 960, "Entra in scena Kozuki Oden"),
      new OnePieceManga(95, 961, "L'incidente dello spirito della montagna"),
      new OnePieceManga(95, 962, "Il Daimyo e i suoi vassalli"),
      new OnePieceManga(95, 963, "Diventare un samurai"),
      new OnePieceManga(95, 964, "L'avventura di Oden"),
      new OnePieceManga(96, 965, "La congiura del clan Kurozumi"),
      new OnePieceManga(96, 966, "Roger e Barbabianca"),
      new OnePieceManga(96, 967, "L'avventura di Roger"),
      new OnePieceManga(96, 968, "Il ritorno di Oden"),
      new OnePieceManga(96, 969, "Il lord tonto"),
      new OnePieceManga(96, 970, "Oden vs Kaido"),
      new OnePieceManga(96, 971, "Bolliti vivi"),
      new OnePieceManga(96, 972, "Io sono Oden! Nato per bollire!"),
      new OnePieceManga(96, 973, "Il clan Kozuki"),
      new OnePieceManga(96, 974, "Verso Onigashima!"),
      new OnePieceManga(97, 975, "Il piano di Kin'emon"),
      new OnePieceManga(97, 976, "Lasciate che mi presenti"),
      new OnePieceManga(97, 977, "La festa non inizia ora"),
      new OnePieceManga(97, 978, "Entrano in scena i sei volanti"),
      new OnePieceManga(97, 979, "Problemi familiari"),
      new OnePieceManga(97, 980, "Musica da combattimento"),
      new OnePieceManga(97, 981, "Scontro"),
      new OnePieceManga(97, 982, "Da ruffiano a ruffiano"),
      new OnePieceManga(97, 983, "Tuono"),
      new OnePieceManga(97, 984, "La mia bibbia"),
      new OnePieceManga(98, 985, "Il progetto nuova Onigashima"),
      new OnePieceManga(98, 986, "Il mio nome"),
      new OnePieceManga(98, 987, "La raffinata veste del vassallo"),
      new OnePieceManga(98, 988, "Scusate il ritardo"),
      new OnePieceManga(
        98,
        989,
        "Per qualche motivo, non mi sento come se stessimo perdendo!"
      ),
      new OnePieceManga(98, 990, "Agente solitario"),
      new OnePieceManga(98, 991, "Lasciaci morire!"),
      new OnePieceManga(98, 992, "Resti"),
      new OnePieceManga(98, 993, "Il sogno di Wano"),
      new OnePieceManga(98, 994, "Puoi chiamarmi Yamato"),
      new OnePieceManga(99, 995, "Il giuramento della Kunoichi"),
      new OnePieceManga(99, 996, "L'isola del più forte"),
      new OnePieceManga(99, 997, "Fiamme"),
      new OnePieceManga(99, 998, "Gli Zoan ancestrali"),
      new OnePieceManga(99, 999, "Il sake che ho distillato per bere con te"),
      new OnePieceManga(99, 1000, "Rufy ''Cappello di paglia''"),
      new OnePieceManga(
        99,
        1001,
        "La battaglia decisiva dei mostri di Onigashima"
      ),
      new OnePieceManga(99, 1002, "Imperatori vs nuova generazione"),
      new OnePieceManga(99, 1003, "La notte su una tavola di Go"),
      new OnePieceManga(99, 1004, "Kibi dango"),
      new OnePieceManga(100, 1005, "La bambina demoniaca"),
      new OnePieceManga(100, 1006, "L'onorevole ''Hyogoro dei fiori''"),
      new OnePieceManga(100, 1007, "Il signor Tanuki"),
      new OnePieceManga(
        100,
        1008,
        "Ashura Doji, capo dei banditi del monte atama"
      ),
      new OnePieceManga(100, 1009, "Inferno"),
      new OnePieceManga(100, 1010, "Tonalità del re conquistatore"),
      new OnePieceManga(100, 1011, "Il codice morale dei fagioli rossi"),
      new OnePieceManga(100, 1012, "Fremere"),
      new OnePieceManga(100, 1013, "Anarchy in the BM"),
      new OnePieceManga(100, 1014, "L'attorucolo di una vita intera"),
      new OnePieceManga(100, 1015, "Catene"),
      new OnePieceManga(101, 1016, "Qui parla Tama!"),
      new OnePieceManga(101, 1017, "Ordini"),
      new OnePieceManga(101, 1018, "Jinbe vs Who's Who"),
      new OnePieceManga(101, 1019, "Heliceratops"),
      new OnePieceManga(101, 1020, "Robin vs Black Maria"),
      new OnePieceManga(101, 1021, "Demonio"),
      new OnePieceManga(101, 1022, "Le stelle si prendono la scena!"),
      new OnePieceManga(101, 1023, "Due gocce d'acqua"),
      new OnePieceManga(101, 1024, "Un tale"),
      new OnePieceManga(101, 1025, "Draghi gemelli"),
      new OnePieceManga(102, 1026, "La resa dei conti"),
      new OnePieceManga(102, 1027, "Un problema oltre ogni immaginazione"),
      new OnePieceManga(102, 1028, "Brachioserperus"),
      new OnePieceManga(102, 1029, "La torre"),
      new OnePieceManga(102, 1030, "L'eco dell'impermanenza di tutte le cose"),
      new OnePieceManga(102, 1031, "Il guerriero della scienza"),
      new OnePieceManga(102, 1032, "La spada preferita di Oden"),
      new OnePieceManga(102, 1033, "Shimotsuki Kouzaburou"),
      new OnePieceManga(102, 1034, "Sanji vs. Queen"),
      new OnePieceManga(102, 1035, "Zoro vs. King"),
      new OnePieceManga(103, 1036, "Il bushido è la ricerca della morte"),
      new OnePieceManga(103, 1037, "Otto trigrammi, drago alcolizzato"),
      new OnePieceManga(103, 1038, "Kidd &amp, Law vs. Big Mom"),
      new OnePieceManga(103, 1039, "Ruolo di chiusura"),
      new OnePieceManga(
        103,
        1040,
        "Le ultime preghiere davanti a dei mocciosi"
      ),
      new OnePieceManga(103, 1041, "Komurasaki"),
      new OnePieceManga(103, 1042, "Forte non vuol dire vincitore"),
      new OnePieceManga(103, 1043, "Fino alla nostra morte!"),
      new OnePieceManga(103, 1044, "Il guerriero della liberazione"),
      new OnePieceManga(103, 1045, "Il livello successivo"),
      new OnePieceManga(103, 1046, "Raizo"),
      new OnePieceManga(104, 1047, "Il cielo della capitale"),
      new OnePieceManga(104, 1048, "Vent'anni"),
      new OnePieceManga(104, 1049, "Il mondo a cui aspirare"),
      new OnePieceManga(104, 1050, "Onore"),
      new OnePieceManga(104, 1051, "Kozuki Momonosuke, lo shogun di Wano"),
      new OnePieceManga(104, 1052, "Una nuova mattina"),
      new OnePieceManga(104, 1053, "I nuovi sovrani"),
      new OnePieceManga(104, 1054, "Imperatore fiammante"),
      new OnePieceManga(104, 1055, "La nuova era"),
      new OnePieceManga(105, 1056, "Cross Guild"),
      new OnePieceManga(105, 1057, "Fine"),
      new OnePieceManga(105, 1058, "Il nuovo sovrano"),
      new OnePieceManga(105, 1059, "Ciò che è accaduto al capitano Koby"),
      new OnePieceManga(105, 1060, "Il sogno di Rufy"),
      new OnePieceManga(105, 1061, "Egghead, l'isola del futuro"),
      new OnePieceManga(105, 1062, "Avventura nel paese della scienza"),
      new OnePieceManga(105, 1063, "Tutto ciò che resta della mia famiglia"),
      new OnePieceManga(105, 1064, "Egghead Labo Phase"),
      new OnePieceManga(105, 1065, "I sei Vegapunk"),
      new OnePieceManga(106, 1066, "La volontà di Ohara"),
      new OnePieceManga(106, 1067, "Punk Records"),
      new OnePieceManga(106, 1068, "Il sogno di un genio"),
      new OnePieceManga(106, 1069, "Tutto al mondo nasce dal desiderio"),
      new OnePieceManga(106, 1070, "Gli esseri umani più forti"),
      new OnePieceManga(106, 1071, "L'eroe va all'attacco"),
      new OnePieceManga(106, 1072, "Il peso dei ricordi"),
      new OnePieceManga(106, 1073, "Miss Buckingham Stussy"),
      new OnePieceManga(106, 1074, "Mark III"),
      new OnePieceManga(106, 1075, "Labo Phase Death Game"),
      new OnePieceManga(106, 1076, "Vecchi Amici"),
      new OnePieceManga(107, 1077, "Avresti dovuto accorgermene prima"),
      new OnePieceManga(107, 1078, "Limite di fuga"),
      new OnePieceManga(
        107,
        1079,
        "I pirati del rosso, membro dei quattro imperatori"
      ),
      new OnePieceManga(107, 1080, "L'eroe leggendario"),
      new OnePieceManga(
        107,
        1081,
        "Kuzan, Capitano della Decima Flotta dei Pirati di Barbanera"
      ),
      new OnePieceManga(107, 1082, "Andiamo a prendercelo!"),
      new OnePieceManga(107, 1083, "La verità su quel giorno"),
      new OnePieceManga(107, 1084, "Il tentato omicidio di un drago celeste"),
      new OnePieceManga(107, 1085, "La morte di Nefertari Cobra"),
      new OnePieceManga(107, 1086, "I cinque astri di saggezza"),
      new OnePieceManga(107, 1087, "Navi da boxe"),
      new OnePieceManga(107, 1088, "L'ultima lezione"),
      new OnePieceManga(108, 1089, "Sotto assedio"),
      new OnePieceManga(108, 1090, "Kizaru"),
      new OnePieceManga(108, 1091, "Sentomaru"),
      new OnePieceManga(
        108,
        1092,
        "L'irruzione di Orso ''Il Tiranno'' nella Terra Santa"
      ),
      new OnePieceManga(108, 1093, "Luffy vs Kizaru"),
      new OnePieceManga(
        108,
        1094,
        "Jaygarcia Saturn, la Divinità Guerriera della Difesa Scientifica"
      ),
      new OnePieceManga(108, 1095, "Un mondo in cui è meglio morire"),
      new OnePieceManga(108, 1096, "Orsacchiotto"),
      new OnePieceManga(108, 1097, "Jinney"),
      new OnePieceManga(108, 1098, "La nascita di Bonney"),
      new OnePieceManga(108, 1099, "Pacifista"),
      new OnePieceManga(108, 1100, "Grazie, Bonney"),
      new OnePieceManga(109, 1101, "A Bonney"),
      new OnePieceManga(109, 1102, "La vita di Orso"),
      new OnePieceManga(109, 1103, "Scusa, papà"),
      new OnePieceManga(109, 1104, "Grazie, papà"),
      new OnePieceManga(109, 1105, "L'apice dell'idiozia"),
      new OnePieceManga(109, 1106, "Al tuo fianco"),
      new OnePieceManga(109, 1107, "Ti stavo cercando!"),
      new OnePieceManga(109, 1108, "Mondo, mi ricevi?"),
      new OnePieceManga(109, 1109, "Intralcio"),
      new OnePieceManga(109, 1110, "La discesa degli astri"),
      new OnePieceManga(110, 1111, "Lo scudo del sole"),
      new OnePieceManga(110, 1112, "Hard Aspect"),
      new OnePieceManga(110, 1113, "Stalemate"),
      new OnePieceManga(110, 1114, "Le ali di Icaro"),
      new OnePieceManga(110, 1115, "Frammenti di continenti"),
      new OnePieceManga(110, 1116, "Conflitti"),
      new OnePieceManga(110, 1117, "Voi"),
      new OnePieceManga(110, 1118, "Più libera che mai"),
      new OnePieceManga(110, 1119, "Emeth"),
      new OnePieceManga(110, 1120, "Atlas"),
      new OnePieceManga(110, 1121, "Il fluire del tempo"),
      new OnePieceManga(111, 1122, "Quando verrà il momento"),
      new OnePieceManga(111, 1123, "Le due settimane di vuoto"),
      new OnePieceManga(111, 1124, "Un caro amico"),
      new OnePieceManga(111, 1125, "Come pensi di procedere?"),
      new OnePieceManga(111, 1126, "Risolvere la questione"),
      new OnePieceManga(111, 1127, "Avventura nel paese del mistero"),
      new OnePieceManga(111, 1128, "RPG"),
      new OnePieceManga(111, 1129, "Livdoll"),
      new OnePieceManga(111, 1130, "Il principe maledetto"),
      new OnePieceManga(111, 1131, "Loki dell'oltretomba"),
      new OnePieceManga(111, 1132, "Avventura ad Elbaph"),
      new OnePieceManga(111, 1133, "Conta solo che tu sia felice"),
      new OnePieceManga(112, 1134, "La biblioteca del gufo"),
      new OnePieceManga(112, 1135, "Le coppe della fratellanza"),
      new OnePieceManga(112, 1136, "Il regno che attende il sole"),
      new OnePieceManga(112, 1137, "Shamrock entra in scena"),
      new OnePieceManga(112, 1138, "L'Harley"),
      new OnePieceManga(112, 1139, "Il divoramontagne"),
      new OnePieceManga(112, 1140, "Scopper Gaban"),
      new OnePieceManga(112, 1141, "Le donne più vecchie di me"),
      new OnePieceManga(112, 1142, "Ciò che più mi spaventa"),
      new OnePieceManga(112, 1143, "I cavalieri degli dei"),
      new OnePieceManga(112, 1144, "L'ora dei guerrieri"),
      new OnePieceManga(
        113,
        1145,
        "L'incendio nel secondo distretto della forestale sull'ottava strada dell'albero"
      ),
      new OnePieceManga(113, 1146, "Nella quiete, il moto"),
      new OnePieceManga(113, 1147, "Ciò che più ci spaventa"),
      new OnePieceManga(113, 1148, "Ronja"),
      new OnePieceManga(113, 1149, "Un secondo"),
      new OnePieceManga(113, 1150, "Domi reversi"),
      new OnePieceManga(113, 1151, "E' tutto chiaro!!!"),
      new OnePieceManga(113, 1152, "Un giorno orribile"),
      new OnePieceManga(113, 1153, "La nascita di Loki"),
      new OnePieceManga(113, 1154, "Non riesco nemmeno a morire"),
      new OnePieceManga(113, 1155, "I pirati di Rocks"),
      new OnePieceManga(114, 1156, "Idol"),
      new OnePieceManga(114, 1157, "Il bar leggendario"),
      new OnePieceManga(114, 1158, "Rocks vs. Harald"),
      new OnePieceManga(114, 1159, "L'isola del destino"),
      new OnePieceManga(114, 1160, "L'incidente di God Valley"),
      new OnePieceManga(
        114,
        1161,
        "Una poesia d'amore scritta sotto una pioggia di frecce"
      ),
      new OnePieceManga(114, 1162, "G.V.B.R."),
      new OnePieceManga(114, 1163, "La promessa"),
      new OnePieceManga(114, 1164, "Il sangue dei Davy"),
    ];
  }

  getVolume(volume) {
    return this.mangaArray.find((manga) => manga.Volume === volume);
  }

  getCapitolo(capitolo) {
    return this.mangaArray.find((manga) => manga.Capitolo === capitolo);
  }

getTitolo(volume, capitolo) {
  const manga = this.mangaArray.find(
    (m) => m.Volume == volume && m.Capitolo == capitolo
  );

  if (!manga) {
    // Nessun elemento trovato
    console.warn(`⚠️ Nessun titolo trovato per Volume ${volume}, Capitolo ${capitolo}`);
    return "Titolo non disponibile";
  }

  // Se esiste, restituisci il titolo
  return manga.Titolo && manga.Titolo.trim() !== ""
    ? manga.Titolo
    : "Titolo non disponibile";
}
}

